// Auto-generated squad data — do not edit manually

const teamSlugs = {
    'Algeria': 'algeria',
    'Argentina': 'argentina',
    'Australia': 'australia',
    'Austria': 'austria',
    'Belgium': 'belgium',
    'Bosnia and Herzegovina': 'bosnia-herzegovina',
    'Brazil': 'brazil',
    'Canada': 'canada',
    'Cape Verde': 'cabo-verde',
    'Colombia': 'colombia',
    'Croatia': 'croatia',
    'Curaçao': 'curacao',
    'Czechia': 'czechia',
    'DR Congo': 'congo-dr',
    'Ecuador': 'ecuador',
    'Egypt': 'egypt',
    'England': 'england',
    'France': 'france',
    'Germany': 'germany',
    'Ghana': 'ghana',
    'Haiti': 'haiti',
    'Iran': 'ir-iran',
    'Iraq': 'iraq',
    'Ivory Coast': 'cote-d-ivoire',
    'Japan': 'japan',
    'Jordan': 'jordan',
    'Mexico': 'mexico',
    'Morocco': 'morocco',
    'Netherlands': 'netherlands',
    'New Zealand': 'new-zealand',
    'Norway': 'norway',
    'Panama': 'panama',
    'Paraguay': 'paraguay',
    'Portugal': 'portugal',
    'Qatar': 'qatar',
    'Saudi Arabia': 'saudi-arabia',
    'Scotland': 'scotland',
    'Senegal': 'senegal',
    'South Africa': 'south-africa',
    'South Korea': 'korea-republic',
    'Spain': 'spain',
    'Sweden': 'sweden',
    'Switzerland': 'switzerland',
    'Tunisia': 'tunisia',
    'Türkiye': 'turkiye',
    'USA': 'usa',
    'Uruguay': 'uruguay',
    'Uzbekistan': 'uzbekistan',
};

const teamsData = {
    'Algeria': {
        coach: '', formation: '',
        players: [
            { num: 1, name: 'Melvin Mastil', pos: 'GK', img: '' },
            { num: 2, name: 'Oussama Benbot', pos: 'GK', img: '' },
            { num: 3, name: 'Luca Zidane', pos: 'GK', img: '' },
            { num: 4, name: 'Aissa Mandi', pos: 'DEF', img: '' },
            { num: 5, name: 'Achref Abada', pos: 'DEF', img: '' },
            { num: 6, name: 'Mohamed Amine Tougai', pos: 'DEF', img: '' },
            { num: 7, name: 'Zineddine Belaid', pos: 'DEF', img: '' },
            { num: 8, name: 'Jaouen Hadjam', pos: 'DEF', img: '' },
            { num: 9, name: 'Rayan Ait-nouri', pos: 'DEF', img: '' },
            { num: 10, name: 'Rafik Belghali', pos: 'DEF', img: '' },
            { num: 11, name: 'Ramy Bensebaini', pos: 'DEF', img: '' },
            { num: 12, name: 'Samir Chergui', pos: 'DEF', img: '' },
            { num: 13, name: 'Ramiz Zerrouki', pos: 'MID', img: '' },
            { num: 14, name: 'Houssem Aouar', pos: 'MID', img: '' },
            { num: 15, name: 'Fares Chaibi', pos: 'MID', img: '' },
            { num: 16, name: 'Hicham Boudaoui', pos: 'MID', img: '' },
            { num: 17, name: 'Nabil Bentaleb', pos: 'MID', img: '' },
            { num: 18, name: 'Ibrahim Maza', pos: 'MID', img: '' },
            { num: 19, name: 'Yassine Titraoui', pos: 'MID', img: '' },
            { num: 20, name: 'Riyad Mahrez', pos: 'FWD', img: '' },
            { num: 21, name: 'Amine Gouiri', pos: 'FWD', img: '' },
            { num: 22, name: 'Anis Hadj Moussa', pos: 'FWD', img: '' },
            { num: 23, name: 'Nadhir Benbouali', pos: 'FWD', img: '' },
            { num: 24, name: 'Mohamed Amoura', pos: 'FWD', img: '' },
            { num: 25, name: 'Adil Boulbina', pos: 'FWD', img: '' },
            { num: 26, name: 'Fares Ghedjemis', pos: 'FWD', img: '' },
        ]
    },
    'Argentina': {
        coach: '', formation: '',
        players: [
            { num: 1, name: 'Juan Musso', pos: 'GK', img: '' },
            { num: 2, name: 'Geronimo Rulli', pos: 'GK', img: '' },
            { num: 3, name: 'Emiliano Martinez', pos: 'GK', img: '' },
            { num: 4, name: 'Nicolas Tagliafico', pos: 'DEF', img: '' },
            { num: 5, name: 'Gonzalo Montiel', pos: 'DEF', img: '' },
            { num: 6, name: 'Lisandro Martinez', pos: 'DEF', img: '' },
            { num: 7, name: 'Cristian Romero', pos: 'DEF', img: '' },
            { num: 8, name: 'Nicolas Otamendi', pos: 'DEF', img: '' },
            { num: 9, name: 'Facundo Medina', pos: 'DEF', img: '' },
            { num: 10, name: 'Nahuel Molina', pos: 'DEF', img: '' },
            { num: 11, name: 'Marcos Senesi', pos: 'MID', img: '' },
            { num: 12, name: 'Leandro Paredes', pos: 'MID', img: '' },
            { num: 13, name: 'Rodrigo De Paul', pos: 'MID', img: '' },
            { num: 14, name: 'Valentin Barco', pos: 'MID', img: '' },
            { num: 15, name: 'Giovani Lo Celso', pos: 'MID', img: '' },
            { num: 16, name: 'Exequiel Palacios', pos: 'MID', img: '' },
            { num: 17, name: 'Nico Gonzalez', pos: 'MID', img: '' },
            { num: 18, name: 'Alexis Mac Allister', pos: 'MID', img: '' },
            { num: 19, name: 'Enzo Fernandez', pos: 'MID', img: '' },
            { num: 20, name: 'Julian Alvarez', pos: 'FWD', img: '' },
            { num: 21, name: 'Lionel Messi', pos: 'FWD', img: '' },
            { num: 22, name: 'Thiago Almada', pos: 'FWD', img: '' },
            { num: 23, name: 'Giuliano Simeone', pos: 'FWD', img: '' },
            { num: 24, name: 'Nico Paz', pos: 'FWD', img: '' },
            { num: 25, name: 'Jose Manuel Lopez', pos: 'FWD', img: '' },
            { num: 26, name: 'Lautaro Martinez', pos: 'FWD', img: '' },
        ]
    },
    'Australia': {
        coach: '', formation: '',
        players: [
            { num: 1, name: 'Mathew Ryan', pos: 'GK', img: '' },
            { num: 2, name: 'Paul Izzo', pos: 'GK', img: '' },
            { num: 3, name: 'Patrick Beach', pos: 'GK', img: '' },
            { num: 4, name: 'Milos Degenek', pos: 'DEF', img: '' },
            { num: 5, name: 'Alessandro Circati', pos: 'DEF', img: '' },
            { num: 6, name: 'Jacob Italiano', pos: 'DEF', img: '' },
            { num: 7, name: 'Jordan Bos', pos: 'DEF', img: '' },
            { num: 8, name: 'Jason Geria', pos: 'DEF', img: '' },
            { num: 9, name: 'Kai Trewin', pos: 'DEF', img: '' },
            { num: 10, name: 'Aziz Behich', pos: 'DEF', img: '' },
            { num: 11, name: 'Harry Souttar', pos: 'DEF', img: '' },
            { num: 12, name: 'Cameron Burgess', pos: 'DEF', img: '' },
            { num: 13, name: 'Lucas Herrington', pos: 'DEF', img: '' },
            { num: 14, name: 'Connor Metcalfe', pos: 'MID', img: '' },
            { num: 15, name: 'Aiden Oneill', pos: 'MID', img: '' },
            { num: 16, name: 'Cameron Devlin', pos: 'MID', img: '' },
            { num: 17, name: 'Jackson Irvine', pos: 'MID', img: '' },
            { num: 18, name: 'Paul Okon-engstler', pos: 'MID', img: '' },
            { num: 19, name: 'Mathew Leckie', pos: 'FWD', img: '' },
            { num: 20, name: 'Mohamed Toure', pos: 'FWD', img: '' },
            { num: 21, name: 'Ajdin Hrustic', pos: 'FWD', img: '' },
            { num: 22, name: 'Awer Mabil', pos: 'FWD', img: '' },
            { num: 23, name: 'Nestory Irankunda', pos: 'FWD', img: '' },
            { num: 24, name: 'Cristian Volpato', pos: 'FWD', img: '' },
            { num: 25, name: 'Nishan Velupillay', pos: 'FWD', img: '' },
            { num: 26, name: 'Tete Yengi', pos: 'FWD', img: '' },
        ]
    },
    'Austria': {
        coach: '', formation: '',
        players: [
            { num: 1, name: 'Alexander Schlager', pos: 'GK', img: '' },
            { num: 2, name: 'Florian Wiegele', pos: 'GK', img: '' },
            { num: 3, name: 'Patrick Pentz', pos: 'GK', img: '' },
            { num: 4, name: 'David Affengruber', pos: 'DEF', img: '' },
            { num: 5, name: 'Kevin Danso', pos: 'DEF', img: '' },
            { num: 6, name: 'Stefan Posch', pos: 'DEF', img: '' },
            { num: 7, name: 'David Alaba', pos: 'DEF', img: '' },
            { num: 8, name: 'Philipp Lienhart', pos: 'DEF', img: '' },
            { num: 9, name: 'Phillip Mwene', pos: 'DEF', img: '' },
            { num: 10, name: 'Marco Friedl', pos: 'DEF', img: '' },
            { num: 11, name: 'Michael Svoboda', pos: 'DEF', img: '' },
            { num: 12, name: 'Xaver Schlager', pos: 'MID', img: '' },
            { num: 13, name: 'Nicolas Seiwald', pos: 'MID', img: '' },
            { num: 14, name: 'Marcel Sabitzer', pos: 'MID', img: '' },
            { num: 15, name: 'Florian Grillitsch', pos: 'MID', img: '' },
            { num: 16, name: 'Carney Chukwuemeka', pos: 'MID', img: '' },
            { num: 17, name: 'Romano Schmid', pos: 'MID', img: '' },
            { num: 18, name: 'Dejan Ljubicic', pos: 'MID', img: '' },
            { num: 19, name: 'Konrad Laimer', pos: 'MID', img: '' },
            { num: 20, name: 'Alexander Prass', pos: 'MID', img: '' },
            { num: 21, name: 'Paul Wanner', pos: 'MID', img: '' },
            { num: 22, name: 'Alessandro Schoepf', pos: 'MID', img: '' },
            { num: 23, name: 'Marko Arnautovic', pos: 'FWD', img: '' },
            { num: 24, name: 'Michael Gregoritsch', pos: 'FWD', img: '' },
            { num: 25, name: 'Sasa Kalajdzic', pos: 'FWD', img: '' },
            { num: 26, name: 'Patrick Wimmer', pos: 'FWD', img: '' },
        ]
    },
    'Belgium': {
        coach: '', formation: '',
        players: [
            { num: 1, name: 'Thibaut Courtois', pos: 'GK', img: '' },
            { num: 2, name: 'Senne Lammens', pos: 'GK', img: '' },
            { num: 3, name: 'Mike Penders', pos: 'GK', img: '' },
            { num: 4, name: 'Zeno Debast', pos: 'DEF', img: '' },
            { num: 5, name: 'Arthur Theate', pos: 'DEF', img: '' },
            { num: 6, name: 'Brandon Mechele', pos: 'DEF', img: '' },
            { num: 7, name: 'Maxim De Cuyper', pos: 'DEF', img: '' },
            { num: 8, name: 'Thomas Meunier', pos: 'DEF', img: '' },
            { num: 9, name: 'Koni De Winter', pos: 'DEF', img: '' },
            { num: 10, name: 'Joaquin Seys', pos: 'DEF', img: '' },
            { num: 11, name: 'Timothy Castagne', pos: 'DEF', img: '' },
            { num: 12, name: 'Nathan Ngoy', pos: 'DEF', img: '' },
            { num: 13, name: 'Axel Witsel', pos: 'MID', img: '' },
            { num: 14, name: 'Kevin De Bruyne', pos: 'MID', img: '' },
            { num: 15, name: 'Youri Tielemans', pos: 'MID', img: '' },
            { num: 16, name: 'Diego Moreira', pos: 'MID', img: '' },
            { num: 17, name: 'Hans Vanaken', pos: 'MID', img: '' },
            { num: 18, name: 'Alexis Saelemaekers', pos: 'MID', img: '' },
            { num: 19, name: 'Nicolas Raskin', pos: 'MID', img: '' },
            { num: 20, name: 'Amadou Onana', pos: 'MID', img: '' },
            { num: 21, name: 'Romelu Lukaku', pos: 'FWD', img: '' },
            { num: 22, name: 'Leandro Trossard', pos: 'FWD', img: '' },
            { num: 23, name: 'Jeremy Doku', pos: 'FWD', img: '' },
            { num: 24, name: 'Dodi Lukebakio', pos: 'FWD', img: '' },
            { num: 25, name: 'Charles De Ketelaere', pos: 'FWD', img: '' },
            { num: 26, name: 'Matias Fernandez-pardo', pos: 'FWD', img: '' },
        ]
    },
    'Bosnia and Herzegovina': {
        coach: '', formation: '',
        players: [
            { num: 1, name: 'Nikola Vasilj', pos: 'GK', img: '' },
            { num: 2, name: 'Mladen Jurkas', pos: 'GK', img: '' },
            { num: 3, name: 'Martin Zlomislic', pos: 'GK', img: '' },
            { num: 4, name: 'Nihad Mujakic', pos: 'DEF', img: '' },
            { num: 5, name: 'Dennis Hadzikadunic', pos: 'DEF', img: '' },
            { num: 6, name: 'Tarik Muharemovic', pos: 'DEF', img: '' },
            { num: 7, name: 'Sead Kolasinac', pos: 'DEF', img: '' },
            { num: 8, name: 'Amar Dedic', pos: 'DEF', img: '' },
            { num: 9, name: 'Nikola Katic', pos: 'DEF', img: '' },
            { num: 10, name: 'Stjepan Radeljic', pos: 'DEF', img: '' },
            { num: 11, name: 'Arjan Malic', pos: 'DEF', img: '' },
            { num: 12, name: 'Benjamin Tahirovic', pos: 'MID', img: '' },
            { num: 13, name: 'Armin Gigovic', pos: 'MID', img: '' },
            { num: 14, name: 'Ivan Basic', pos: 'MID', img: '' },
            { num: 15, name: 'Ivan Sunjic', pos: 'MID', img: '' },
            { num: 16, name: 'Amar Memic', pos: 'MID', img: '' },
            { num: 17, name: 'Amir Hadziahmetovic', pos: 'MID', img: '' },
            { num: 18, name: 'Dzenis Burnic', pos: 'MID', img: '' },
            { num: 19, name: 'Ermin Mahmic', pos: 'MID', img: '' },
            { num: 20, name: 'Samed Bazdar', pos: 'FWD', img: '' },
            { num: 21, name: 'Ermedin Demirovic', pos: 'FWD', img: '' },
            { num: 22, name: 'Edin Dzeko', pos: 'FWD', img: '' },
            { num: 23, name: 'Kerim Alajbegovic', pos: 'FWD', img: '' },
            { num: 24, name: 'Esmir Bajraktarevic', pos: 'FWD', img: '' },
            { num: 25, name: 'Haris Tabakovic', pos: 'FWD', img: '' },
            { num: 26, name: 'Jovo Lukic', pos: 'FWD', img: '' },
        ]
    },
    'Brazil': {
        coach: '', formation: '',
        players: [
            { num: 1, name: 'Alisson', pos: 'GK', img: '' },
            { num: 2, name: 'Weverton', pos: 'GK', img: '' },
            { num: 3, name: 'Ederson', pos: 'GK', img: '' },
            { num: 4, name: 'Gabriel Magalhaes', pos: 'DEF', img: '' },
            { num: 5, name: 'Marquinhos', pos: 'DEF', img: '' },
            { num: 6, name: 'Alex Sandro', pos: 'DEF', img: '' },
            { num: 7, name: 'Danilo', pos: 'DEF', img: '' },
            { num: 8, name: 'Bremer', pos: 'DEF', img: '' },
            { num: 9, name: 'Leo Pereira', pos: 'DEF', img: '' },
            { num: 10, name: 'Douglas Santos', pos: 'DEF', img: '' },
            { num: 11, name: 'Roger Ibanez', pos: 'DEF', img: '' },
            { num: 12, name: 'Ederson Silva', pos: 'MID', img: '' },
            { num: 13, name: 'Casemiro', pos: 'MID', img: '' },
            { num: 14, name: 'Bruno Guimaraes', pos: 'MID', img: '' },
            { num: 15, name: 'Fabinho', pos: 'MID', img: '' },
            { num: 16, name: 'Danilo Santos', pos: 'MID', img: '' },
            { num: 17, name: 'Lucas Paqueta', pos: 'MID', img: '' },
            { num: 18, name: 'Vinicius Junior', pos: 'FWD', img: '' },
            { num: 19, name: 'Matheus Cunha', pos: 'FWD', img: '' },
            { num: 20, name: 'Neymar Jr', pos: 'FWD', img: '' },
            { num: 21, name: 'Raphinha', pos: 'FWD', img: '' },
            { num: 22, name: 'Endrick', pos: 'FWD', img: '' },
            { num: 23, name: 'Luiz Henrique', pos: 'FWD', img: '' },
            { num: 24, name: 'Gabriel Martinelli', pos: 'FWD', img: '' },
            { num: 25, name: 'Igor Thiago', pos: 'FWD', img: '' },
            { num: 26, name: 'Rayan', pos: 'FWD', img: '' },
        ]
    },
    'Canada': {
        coach: '', formation: '',
        players: [
            { num: 1, name: 'Dayne St. Clair', pos: 'GK', img: '' },
            { num: 2, name: 'Maxime Crepeau', pos: 'GK', img: '' },
            { num: 3, name: 'Owen Goodman', pos: 'GK', img: '' },
            { num: 4, name: 'Alistair Johnston', pos: 'DEF', img: '' },
            { num: 5, name: 'Alfie Jones', pos: 'DEF', img: '' },
            { num: 6, name: 'Luc De Fougerolles', pos: 'DEF', img: '' },
            { num: 7, name: 'Joel Waterman', pos: 'DEF', img: '' },
            { num: 8, name: 'Derek Cornelius', pos: 'DEF', img: '' },
            { num: 9, name: 'Moise Bombito', pos: 'DEF', img: '' },
            { num: 10, name: 'Alphonso Davies', pos: 'DEF', img: '' },
            { num: 11, name: 'Richie Laryea', pos: 'DEF', img: '' },
            { num: 12, name: 'Niko Sigur', pos: 'DEF', img: '' },
            { num: 13, name: 'Mathieu Choiniere', pos: 'MID', img: '' },
            { num: 14, name: 'Stephen Eustaquio', pos: 'MID', img: '' },
            { num: 15, name: 'Ismael Kone', pos: 'MID', img: '' },
            { num: 16, name: 'Liam Millar', pos: 'MID', img: '' },
            { num: 17, name: 'Jacob Shaffelburg', pos: 'MID', img: '' },
            { num: 18, name: 'Jonathan Osorio', pos: 'MID', img: '' },
            { num: 19, name: 'Nathan Saliba', pos: 'MID', img: '' },
            { num: 20, name: 'Cyle Larin', pos: 'FWD', img: '' },
            { num: 21, name: 'Jonathan David', pos: 'FWD', img: '' },
            { num: 22, name: 'Tani Oluwaseyi', pos: 'FWD', img: '' },
            { num: 23, name: 'Tajon Buchanan', pos: 'FWD', img: '' },
            { num: 24, name: 'Ali Ahmed', pos: 'FWD', img: '' },
            { num: 25, name: 'Promise David', pos: 'FWD', img: '' },
            { num: 26, name: 'Jayden Nelson', pos: 'FWD', img: '' },
        ]
    },
    'Cape Verde': {
        coach: '', formation: '',
        players: [
            { num: 1, name: 'Vozinha', pos: 'GK', img: '' },
            { num: 2, name: 'Marcio Rosa', pos: 'GK', img: '' },
            { num: 3, name: 'Cj Dos Santos', pos: 'GK', img: '' },
            { num: 4, name: 'Stopira', pos: 'DEF', img: '' },
            { num: 5, name: 'Diney Borges', pos: 'DEF', img: '' },
            { num: 6, name: 'Pico Lopes', pos: 'DEF', img: '' },
            { num: 7, name: 'Logan Costa', pos: 'DEF', img: '' },
            { num: 8, name: 'Sidny Lopes Cabral', pos: 'DEF', img: '' },
            { num: 9, name: 'Steven Moreira', pos: 'DEF', img: '' },
            { num: 10, name: 'Wagner Pina', pos: 'DEF', img: '' },
            { num: 11, name: 'Kelvin Pires', pos: 'DEF', img: '' },
            { num: 12, name: 'Kevin Pina', pos: 'MID', img: '' },
            { num: 13, name: 'Jovane Cabral', pos: 'MID', img: '' },
            { num: 14, name: 'Joao Paulo', pos: 'MID', img: '' },
            { num: 15, name: 'Jamiro Monteiro', pos: 'MID', img: '' },
            { num: 16, name: 'Garry Rodrigues', pos: 'MID', img: '' },
            { num: 17, name: 'Deroy Duarte', pos: 'MID', img: '' },
            { num: 18, name: 'Laros Duarte', pos: 'MID', img: '' },
            { num: 19, name: 'Yannick Semedo', pos: 'MID', img: '' },
            { num: 20, name: 'Willy Semedo', pos: 'MID', img: '' },
            { num: 21, name: 'Telmo Arcanjo', pos: 'MID', img: '' },
            { num: 22, name: 'Nuno Da Costa', pos: 'MID', img: '' },
            { num: 23, name: 'Helio Varela', pos: 'MID', img: '' },
            { num: 24, name: 'Gilson Benchimol', pos: 'FWD', img: '' },
            { num: 25, name: 'Dailon Livramento', pos: 'FWD', img: '' },
            { num: 26, name: 'Ryan Mendes', pos: 'FWD', img: '' },
        ]
    },
    'Colombia': {
        coach: '', formation: '',
        players: [
            { num: 1, name: 'David Ospina', pos: 'GK', img: '' },
            { num: 2, name: 'Camilo Vargas', pos: 'GK', img: '' },
            { num: 3, name: 'Alvaro Montero', pos: 'GK', img: '' },
            { num: 4, name: 'Daniel Munoz', pos: 'DEF', img: '' },
            { num: 5, name: 'Jhon Lucumi', pos: 'DEF', img: '' },
            { num: 6, name: 'Santiago Arias', pos: 'DEF', img: '' },
            { num: 7, name: 'Yerry Mina', pos: 'DEF', img: '' },
            { num: 8, name: 'Gustavo Puerta', pos: 'DEF', img: '' },
            { num: 9, name: 'Johan Mojica', pos: 'DEF', img: '' },
            { num: 10, name: 'Willer Ditta', pos: 'DEF', img: '' },
            { num: 11, name: 'Deiver Machado', pos: 'DEF', img: '' },
            { num: 12, name: 'Davinson Sanchez', pos: 'DEF', img: '' },
            { num: 13, name: 'Kevin Castano', pos: 'MID', img: '' },
            { num: 14, name: 'Richard Rios', pos: 'MID', img: '' },
            { num: 15, name: 'Jorge Carrascal', pos: 'MID', img: '' },
            { num: 16, name: 'James Rodriguez', pos: 'MID', img: '' },
            { num: 17, name: 'Jhon Arias', pos: 'MID', img: '' },
            { num: 18, name: 'Juan Portilla', pos: 'MID', img: '' },
            { num: 19, name: 'Jefferson Lerma', pos: 'MID', img: '' },
            { num: 20, name: 'Juan Quintero', pos: 'MID', img: '' },
            { num: 21, name: 'Luis Diaz', pos: 'FWD', img: '' },
            { num: 22, name: 'Jhon Cordoba', pos: 'FWD', img: '' },
            { num: 23, name: 'Cucho Hernandez', pos: 'FWD', img: '' },
            { num: 24, name: 'Jaminton Campaz', pos: 'FWD', img: '' },
            { num: 25, name: 'Luis Suarez', pos: 'FWD', img: '' },
            { num: 26, name: 'Andres Gomez', pos: 'FWD', img: '' },
        ]
    },
    'Croatia': {
        coach: '', formation: '',
        players: [
            { num: 1, name: 'Dominik Livakovic', pos: 'GK', img: '' },
            { num: 2, name: 'Ivor Pandur', pos: 'GK', img: '' },
            { num: 3, name: 'Dominik Kotarski', pos: 'GK', img: '' },
            { num: 4, name: 'Josip Stanisic', pos: 'DEF', img: '' },
            { num: 5, name: 'Marin Pongracic', pos: 'DEF', img: '' },
            { num: 6, name: 'Josko Gvardiol', pos: 'DEF', img: '' },
            { num: 7, name: 'Duje Caleta-car', pos: 'DEF', img: '' },
            { num: 8, name: 'Josip Sutalo', pos: 'DEF', img: '' },
            { num: 9, name: 'Kristijan Jakic', pos: 'DEF', img: '' },
            { num: 10, name: 'Luka Vuskovic', pos: 'DEF', img: '' },
            { num: 11, name: 'Martin Erlic', pos: 'DEF', img: '' },
            { num: 12, name: 'Nikola Moro', pos: 'MID', img: '' },
            { num: 13, name: 'Mateo Kovacic', pos: 'MID', img: '' },
            { num: 14, name: 'Luka Modric', pos: 'MID', img: '' },
            { num: 15, name: 'Nikola Vlasic', pos: 'MID', img: '' },
            { num: 16, name: 'Mario Pasalic', pos: 'MID', img: '' },
            { num: 17, name: 'Martin Baturina', pos: 'MID', img: '' },
            { num: 18, name: 'Petar Sucic', pos: 'MID', img: '' },
            { num: 19, name: 'Toni Fruk', pos: 'MID', img: '' },
            { num: 20, name: 'Luka Sucic', pos: 'MID', img: '' },
            { num: 21, name: 'Andrej Kramaric', pos: 'FWD', img: '' },
            { num: 22, name: 'Ante Budimir', pos: 'FWD', img: '' },
            { num: 23, name: 'Ivan Perisic', pos: 'FWD', img: '' },
            { num: 24, name: 'Igor Matanovic', pos: 'FWD', img: '' },
            { num: 25, name: 'Marco Pasalic', pos: 'FWD', img: '' },
            { num: 26, name: 'Petar Musa', pos: 'FWD', img: '' },
        ]
    },
    'Curaçao': {
        coach: '', formation: '',
        players: [
            { num: 1, name: 'Eloy Room', pos: 'GK', img: '' },
            { num: 2, name: 'Tyrick Bodak', pos: 'GK', img: '' },
            { num: 3, name: 'Trevor Doornbusch', pos: 'GK', img: '' },
            { num: 4, name: 'Shurandy Sambo', pos: 'DEF', img: '' },
            { num: 5, name: 'Jurien Gaari', pos: 'DEF', img: '' },
            { num: 6, name: 'Roshon Van Eijma', pos: 'DEF', img: '' },
            { num: 7, name: 'Sherel Floranus', pos: 'DEF', img: '' },
            { num: 8, name: 'Armando Obispo', pos: 'DEF', img: '' },
            { num: 9, name: 'Joshua Brenet', pos: 'DEF', img: '' },
            { num: 10, name: 'Riechedly Bazoer', pos: 'DEF', img: '' },
            { num: 11, name: 'Deveron Fonville', pos: 'DEF', img: '' },
            { num: 12, name: 'Godfried Roemeratoe', pos: 'MID', img: '' },
            { num: 13, name: 'Juninho Bacuna', pos: 'MID', img: '' },
            { num: 14, name: 'Livano Comenencia', pos: 'MID', img: '' },
            { num: 15, name: 'Leandro Bacuna', pos: 'MID', img: '' },
            { num: 16, name: 'Arjany Martha', pos: 'MID', img: '' },
            { num: 17, name: 'Tahith Chong', pos: 'MID', img: '' },
            { num: 18, name: 'Kevin Felida', pos: 'MID', img: '' },
            { num: 19, name: 'Juergen Locadia', pos: 'FWD', img: '' },
            { num: 20, name: 'Jeremy Antonisse', pos: 'FWD', img: '' },
            { num: 21, name: 'Sontje Hansen', pos: 'FWD', img: '' },
            { num: 22, name: 'Tyrese Noslin', pos: 'FWD', img: '' },
            { num: 23, name: 'Kenji Gorre', pos: 'FWD', img: '' },
            { num: 24, name: 'Jearl Margaritha', pos: 'FWD', img: '' },
            { num: 25, name: 'Brandley Kuwas', pos: 'FWD', img: '' },
            { num: 26, name: 'Gervane Kastaneer', pos: 'FWD', img: '' },
        ]
    },
    'Czechia': {
        coach: '', formation: '',
        players: [
        ]
    },
    'DR Congo': {
        coach: '', formation: '',
        players: [
            { num: 1, name: 'Lionel Mpasi', pos: 'GK', img: '' },
            { num: 2, name: 'Timothy Fayulu', pos: 'GK', img: '' },
            { num: 3, name: 'Matthieu Epolo', pos: 'GK', img: '' },
            { num: 4, name: 'Aaron Wan-bissaka', pos: 'DEF', img: '' },
            { num: 5, name: 'Steve Kapuadi', pos: 'DEF', img: '' },
            { num: 6, name: 'Axel Tuanzebe', pos: 'DEF', img: '' },
            { num: 7, name: 'Dylan Batubinsika', pos: 'DEF', img: '' },
            { num: 8, name: 'Joris Kayembe', pos: 'DEF', img: '' },
            { num: 9, name: 'Chancel Mbemba', pos: 'DEF', img: '' },
            { num: 10, name: 'Gedeon Kalulu', pos: 'DEF', img: '' },
            { num: 11, name: 'Arthur Masuaku', pos: 'DEF', img: '' },
            { num: 12, name: 'Ngalayel Mukau', pos: 'MID', img: '' },
            { num: 13, name: 'Nathanael Mbuku', pos: 'MID', img: '' },
            { num: 14, name: 'Samuel Moutoussamy', pos: 'MID', img: '' },
            { num: 15, name: 'Theo Bongonda', pos: 'MID', img: '' },
            { num: 16, name: 'Noah Sadiki', pos: 'MID', img: '' },
            { num: 17, name: 'Aaron Tshibola', pos: 'MID', img: '' },
            { num: 18, name: 'Charles Pickel', pos: 'MID', img: '' },
            { num: 19, name: 'Edo Kayembe', pos: 'MID', img: '' },
            { num: 20, name: 'Brian Cipenga', pos: 'FWD', img: '' },
            { num: 21, name: 'Gael Kakuta', pos: 'FWD', img: '' },
            { num: 22, name: 'Meschack Elia', pos: 'FWD', img: '' },
            { num: 23, name: 'Cedric Bakambu', pos: 'FWD', img: '' },
            { num: 24, name: 'Fiston Mayele', pos: 'FWD', img: '' },
            { num: 25, name: 'Yoane Wissa', pos: 'FWD', img: '' },
            { num: 26, name: 'Simon Banza', pos: 'FWD', img: '' },
        ]
    },
    'Ecuador': {
        coach: '', formation: '',
        players: [
            { num: 1, name: 'Hernan Galindez', pos: 'GK', img: '' },
            { num: 2, name: 'Moises Ramirez', pos: 'GK', img: '' },
            { num: 3, name: 'Gonzalo Valle', pos: 'GK', img: '' },
            { num: 4, name: 'Felix Torres', pos: 'DEF', img: '' },
            { num: 5, name: 'Piero Hincapie', pos: 'DEF', img: '' },
            { num: 6, name: 'Joel Ordonez', pos: 'DEF', img: '' },
            { num: 7, name: 'Willian Pacho', pos: 'DEF', img: '' },
            { num: 8, name: 'Pervis Estupinan', pos: 'DEF', img: '' },
            { num: 9, name: 'Angelo Preciado', pos: 'DEF', img: '' },
            { num: 10, name: 'Jackson Porozo', pos: 'DEF', img: '' },
            { num: 11, name: 'Yaimar Medina', pos: 'DEF', img: '' },
            { num: 12, name: 'Jordy Alcivar', pos: 'MID', img: '' },
            { num: 13, name: 'Anthony Valencia', pos: 'MID', img: '' },
            { num: 14, name: 'Kendry Paez', pos: 'MID', img: '' },
            { num: 15, name: 'Alan Minda', pos: 'MID', img: '' },
            { num: 16, name: 'Pedro Vite', pos: 'MID', img: '' },
            { num: 17, name: 'Denil Castillo', pos: 'MID', img: '' },
            { num: 18, name: 'Alan Franco', pos: 'MID', img: '' },
            { num: 19, name: 'Moises Caicedo', pos: 'MID', img: '' },
            { num: 20, name: 'John Yeboah', pos: 'FWD', img: '' },
            { num: 21, name: 'Kevin Rodriguez', pos: 'FWD', img: '' },
            { num: 22, name: 'Enner Valencia', pos: 'FWD', img: '' },
            { num: 23, name: 'Jordy Caicedo', pos: 'FWD', img: '' },
            { num: 24, name: 'Gonzalo Plata', pos: 'FWD', img: '' },
            { num: 25, name: 'Nilson Angulo', pos: 'FWD', img: '' },
            { num: 26, name: 'Jeremy Arevalo', pos: 'FWD', img: '' },
        ]
    },
    'Egypt': {
        coach: '', formation: '',
        players: [
            { num: 1, name: 'Mohamed Elshenawy', pos: 'GK', img: '' },
            { num: 2, name: 'Mahdy Soliman', pos: 'GK', img: '' },
            { num: 3, name: 'Mostafa Shoubir', pos: 'GK', img: '' },
            { num: 4, name: 'Mohamed Alaa', pos: 'GK', img: '' },
            { num: 5, name: 'Yasser Ibrahim', pos: 'DEF', img: '' },
            { num: 6, name: 'Mohamed Hany', pos: 'DEF', img: '' },
            { num: 7, name: 'Hossam Abdelmaguid', pos: 'DEF', img: '' },
            { num: 8, name: 'Ramy Rabia', pos: 'DEF', img: '' },
            { num: 9, name: 'Mohamed Abdelmoneim', pos: 'DEF', img: '' },
            { num: 10, name: 'Ahmed Fatouh', pos: 'DEF', img: '' },
            { num: 11, name: 'Karim Hafez', pos: 'DEF', img: '' },
            { num: 12, name: 'Tarek Alaa', pos: 'DEF', img: '' },
            { num: 13, name: 'Emam Ashour', pos: 'MID', img: '' },
            { num: 14, name: 'Mostafa Zico', pos: 'MID', img: '' },
            { num: 15, name: 'Hamdy Fathy', pos: 'MID', img: '' },
            { num: 16, name: 'Mohanad Lashin', pos: 'MID', img: '' },
            { num: 17, name: 'Nabil Donga', pos: 'MID', img: '' },
            { num: 18, name: 'Marawan Attia', pos: 'MID', img: '' },
            { num: 19, name: 'Mahmoud Saber', pos: 'MID', img: '' },
            { num: 20, name: 'Trezeguet', pos: 'FWD', img: '' },
            { num: 21, name: 'Hamza Abdelkarim', pos: 'FWD', img: '' },
            { num: 22, name: 'Mohamed Salah', pos: 'FWD', img: '' },
            { num: 23, name: 'Haissem Hassan', pos: 'FWD', img: '' },
            { num: 24, name: 'Ibrahim Adel', pos: 'FWD', img: '' },
            { num: 25, name: 'Omar Marmoush', pos: 'FWD', img: '' },
            { num: 26, name: 'Zizo', pos: 'FWD', img: '' },
        ]
    },
    'England': {
        coach: '', formation: '',
        players: [
            { num: 1, name: 'Jordan Pickford', pos: 'GK', img: '' },
            { num: 2, name: 'Dean Henderson', pos: 'GK', img: '' },
            { num: 3, name: 'James Trafford', pos: 'GK', img: '' },
            { num: 4, name: 'Ezri Konsa', pos: 'DEF', img: '' },
            { num: 5, name: 'Nico Oreilly', pos: 'DEF', img: '' },
            { num: 6, name: 'John Stones', pos: 'DEF', img: '' },
            { num: 7, name: 'Marc Guehi', pos: 'DEF', img: '' },
            { num: 8, name: 'Tino Livramento', pos: 'DEF', img: '' },
            { num: 9, name: 'Dan Burn', pos: 'DEF', img: '' },
            { num: 10, name: 'Reece James', pos: 'DEF', img: '' },
            { num: 11, name: 'Djed Spence', pos: 'DEF', img: '' },
            { num: 12, name: 'Jarell Quansah', pos: 'DEF', img: '' },
            { num: 13, name: 'Declan Rice', pos: 'MID', img: '' },
            { num: 14, name: 'Elliot Anderson', pos: 'MID', img: '' },
            { num: 15, name: 'Jude Bellingham', pos: 'MID', img: '' },
            { num: 16, name: 'Jordan Henderson', pos: 'MID', img: '' },
            { num: 17, name: 'Kobbie Mainoo', pos: 'MID', img: '' },
            { num: 18, name: 'Morgan Rogers', pos: 'MID', img: '' },
            { num: 19, name: 'Eberechi Eze', pos: 'MID', img: '' },
            { num: 20, name: 'Bukayo Saka', pos: 'FWD', img: '' },
            { num: 21, name: 'Harry Kane', pos: 'FWD', img: '' },
            { num: 22, name: 'Marcus Rashford', pos: 'FWD', img: '' },
            { num: 23, name: 'Anthony Gordon', pos: 'FWD', img: '' },
            { num: 24, name: 'Ollie Watkins', pos: 'FWD', img: '' },
            { num: 25, name: 'Noni Madueke', pos: 'FWD', img: '' },
            { num: 26, name: 'Ivan Toney', pos: 'FWD', img: '' },
        ]
    },
    'France': {
        coach: '', formation: '',
        players: [
            { num: 1, name: 'Brice Samba', pos: 'GK', img: '' },
            { num: 2, name: 'Mike Maignan', pos: 'GK', img: '' },
            { num: 3, name: 'Robin Risser', pos: 'GK', img: '' },
            { num: 4, name: 'Malo Gusto', pos: 'DEF', img: '' },
            { num: 5, name: 'Lucas Digne', pos: 'DEF', img: '' },
            { num: 6, name: 'Dayot Upamecano', pos: 'DEF', img: '' },
            { num: 7, name: 'Jules Kounde', pos: 'DEF', img: '' },
            { num: 8, name: 'Ibrahima Konate', pos: 'DEF', img: '' },
            { num: 9, name: 'William Saliba', pos: 'DEF', img: '' },
            { num: 10, name: 'Theo Hernandez', pos: 'DEF', img: '' },
            { num: 11, name: 'Lucas Hernandez', pos: 'DEF', img: '' },
            { num: 12, name: 'Maxence Lacroix', pos: 'DEF', img: '' },
            { num: 13, name: 'Manu Kone', pos: 'MID', img: '' },
            { num: 14, name: 'Aurelien Tchouameni', pos: 'MID', img: '' },
            { num: 15, name: 'Ngolo Kante', pos: 'MID', img: '' },
            { num: 16, name: 'Adrien Rabiot', pos: 'MID', img: '' },
            { num: 17, name: 'Warren Zaire-emery', pos: 'MID', img: '' },
            { num: 18, name: 'Rayan Cherki', pos: 'MID', img: '' },
            { num: 19, name: 'Maghnes Akliouche', pos: 'MID', img: '' },
            { num: 20, name: 'Ousmane Dembele', pos: 'FWD', img: '' },
            { num: 21, name: 'Marcus Thuram', pos: 'FWD', img: '' },
            { num: 22, name: 'Kylian Mbappe', pos: 'FWD', img: '' },
            { num: 23, name: 'Michael Olise', pos: 'FWD', img: '' },
            { num: 24, name: 'Bradley Barcola', pos: 'FWD', img: '' },
            { num: 25, name: 'Desire Doue', pos: 'FWD', img: '' },
            { num: 26, name: 'Jean-philippe Mateta', pos: 'FWD', img: '' },
        ]
    },
    'Germany': {
        coach: '', formation: '',
        players: [
            { num: 1, name: 'Manuel Neuer', pos: 'GK', img: '' },
            { num: 2, name: 'Oliver Baumann', pos: 'GK', img: '' },
            { num: 3, name: 'Alexander Nuebel', pos: 'GK', img: '' },
            { num: 4, name: 'Antonio Ruediger', pos: 'DEF', img: '' },
            { num: 5, name: 'Waldemar Anton', pos: 'DEF', img: '' },
            { num: 6, name: 'Jonathan Tah', pos: 'DEF', img: '' },
            { num: 7, name: 'Joshua Kimmich', pos: 'DEF', img: '' },
            { num: 8, name: 'Nico Schlotterbeck', pos: 'DEF', img: '' },
            { num: 9, name: 'Nathaniel Brown', pos: 'DEF', img: '' },
            { num: 10, name: 'David Raum', pos: 'DEF', img: '' },
            { num: 11, name: 'Malick Thiaw', pos: 'DEF', img: '' },
            { num: 12, name: 'Aleksandar Pavlovic', pos: 'MID', img: '' },
            { num: 13, name: 'Leon Goretzka', pos: 'MID', img: '' },
            { num: 14, name: 'Jamie Leweling', pos: 'MID', img: '' },
            { num: 15, name: 'Jamal Musiala', pos: 'MID', img: '' },
            { num: 16, name: 'Pascal Gross', pos: 'MID', img: '' },
            { num: 17, name: 'Angelo Stiller', pos: 'MID', img: '' },
            { num: 18, name: 'Florian Wirtz', pos: 'MID', img: '' },
            { num: 19, name: 'Leroy Sane', pos: 'MID', img: '' },
            { num: 20, name: 'Nadiem Amiri', pos: 'MID', img: '' },
            { num: 21, name: 'Felix Nmecha', pos: 'MID', img: '' },
            { num: 22, name: 'Assan Ouedraogo', pos: 'MID', img: '' },
            { num: 23, name: 'Kai Havertz', pos: 'FWD', img: '' },
            { num: 24, name: 'Nick Woltemade', pos: 'FWD', img: '' },
            { num: 25, name: 'Maximilian Beier', pos: 'FWD', img: '' },
            { num: 26, name: 'Deniz Undav', pos: 'FWD', img: '' },
        ]
    },
    'Ghana': {
        coach: '', formation: '',
        players: [
            { num: 1, name: 'Lawrence Ati Zigi', pos: 'GK', img: '' },
            { num: 2, name: 'Joseph Anang', pos: 'GK', img: '' },
            { num: 3, name: 'Benjamin Asare', pos: 'GK', img: '' },
            { num: 4, name: 'Alidu Seidu', pos: 'DEF', img: '' },
            { num: 5, name: 'Jonas Adjetey', pos: 'DEF', img: '' },
            { num: 6, name: 'Abdul Mumin', pos: 'DEF', img: '' },
            { num: 7, name: 'Gideon Mensah', pos: 'DEF', img: '' },
            { num: 8, name: 'Baba Rahman', pos: 'DEF', img: '' },
            { num: 9, name: 'Jerome Opoku', pos: 'DEF', img: '' },
            { num: 10, name: 'Kojo Peprah Oppong', pos: 'DEF', img: '' },
            { num: 11, name: 'Derrick Luckassen', pos: 'DEF', img: '' },
            { num: 12, name: 'Marvin Senaya', pos: 'DEF', img: '' },
            { num: 13, name: 'Caleb Yirenkyi', pos: 'MID', img: '' },
            { num: 14, name: 'Thomas Partey', pos: 'MID', img: '' },
            { num: 15, name: 'Kwasi Sibo', pos: 'MID', img: '' },
            { num: 16, name: 'Antoine Semenyo', pos: 'MID', img: '' },
            { num: 17, name: 'Elisha Owusu', pos: 'MID', img: '' },
            { num: 18, name: 'Augustine Boakye', pos: 'MID', img: '' },
            { num: 19, name: 'Abdul Fatawu', pos: 'FWD', img: '' },
            { num: 20, name: 'Jordan Ayew', pos: 'FWD', img: '' },
            { num: 21, name: 'Brandon Thomas-asante', pos: 'FWD', img: '' },
            { num: 22, name: 'Christopher Bonsu Baah', pos: 'FWD', img: '' },
            { num: 23, name: 'Inaki Williams', pos: 'FWD', img: '' },
            { num: 24, name: 'Kamaldeen Sulemana', pos: 'FWD', img: '' },
            { num: 25, name: 'Ernest Nuamah', pos: 'FWD', img: '' },
            { num: 26, name: 'Prince Adu', pos: 'FWD', img: '' },
        ]
    },
    'Haiti': {
        coach: '', formation: '',
        players: [
            { num: 1, name: 'Johny Placide', pos: 'GK', img: '' },
            { num: 2, name: 'Alexandre Pierre', pos: 'GK', img: '' },
            { num: 3, name: 'Josue Duverger', pos: 'GK', img: '' },
            { num: 4, name: 'Carlens Arcus', pos: 'DEF', img: '' },
            { num: 5, name: 'Keeto Thermoncy', pos: 'DEF', img: '' },
            { num: 6, name: 'Ricardo Ade', pos: 'DEF', img: '' },
            { num: 7, name: 'Hannes Delcroix', pos: 'DEF', img: '' },
            { num: 8, name: 'Martin Experience', pos: 'DEF', img: '' },
            { num: 9, name: 'Markhus Lacroix', pos: 'DEF', img: '' },
            { num: 10, name: 'Garven Metusala', pos: 'DEF', img: '' },
            { num: 11, name: 'Jean-kevin Duverne', pos: 'DEF', img: '' },
            { num: 12, name: 'Wilguens Paugain', pos: 'DEF', img: '' },
            { num: 13, name: 'Carl Sainte', pos: 'MID', img: '' },
            { num: 14, name: 'Jean-ricner Bellegarde', pos: 'MID', img: '' },
            { num: 15, name: 'Danley Jean Jacques', pos: 'MID', img: '' },
            { num: 16, name: 'Dominique Simon', pos: 'MID', img: '' },
            { num: 17, name: 'Woodensky Pierre', pos: 'MID', img: '' },
            { num: 18, name: 'Derrick Etienne', pos: 'FWD', img: '' },
            { num: 19, name: 'Duckens Nazon', pos: 'FWD', img: '' },
            { num: 20, name: 'Louicius Deedson', pos: 'FWD', img: '' },
            { num: 21, name: 'Ruben Providence', pos: 'FWD', img: '' },
            { num: 22, name: 'Lenny Joseph', pos: 'FWD', img: '' },
            { num: 23, name: 'Wilson Isidor', pos: 'FWD', img: '' },
            { num: 24, name: 'Yassin Fortune', pos: 'FWD', img: '' },
            { num: 25, name: 'Frantzdy Pierrot', pos: 'FWD', img: '' },
            { num: 26, name: 'Josue Casimir', pos: 'FWD', img: '' },
        ]
    },
    'Iran': {
        coach: '', formation: '',
        players: [
            { num: 1, name: 'Alireza Beiranvand', pos: 'GK', img: '' },
            { num: 2, name: 'Payam Niazmand', pos: 'GK', img: '' },
            { num: 3, name: 'Hossein Hosseini', pos: 'GK', img: '' },
            { num: 4, name: 'Saleh Hardani', pos: 'DEF', img: '' },
            { num: 5, name: 'Ehsan Hajisafi', pos: 'DEF', img: '' },
            { num: 6, name: 'Shoja Khalilzadeh', pos: 'DEF', img: '' },
            { num: 7, name: 'Milad Mohammadi', pos: 'DEF', img: '' },
            { num: 8, name: 'Hossein Kanani', pos: 'DEF', img: '' },
            { num: 9, name: 'Arya Yousefi', pos: 'DEF', img: '' },
            { num: 10, name: 'Ali Nemati', pos: 'DEF', img: '' },
            { num: 11, name: 'Ramin Rezaeian', pos: 'DEF', img: '' },
            { num: 12, name: 'Danial Iri', pos: 'DEF', img: '' },
            { num: 13, name: 'Saeid Ezatolahi', pos: 'MID', img: '' },
            { num: 14, name: 'Alireza Jahanbakhsh', pos: 'MID', img: '' },
            { num: 15, name: 'Mohammad Mohebbi', pos: 'MID', img: '' },
            { num: 16, name: 'Saman Ghoddos', pos: 'MID', img: '' },
            { num: 17, name: 'Roozbeh Cheshmi', pos: 'MID', img: '' },
            { num: 18, name: 'Mehdi Torabi', pos: 'MID', img: '' },
            { num: 19, name: 'Mohammad Ghorbani', pos: 'MID', img: '' },
            { num: 20, name: 'Amirmohammad Razaghinia', pos: 'MID', img: '' },
            { num: 21, name: 'Mehdi Taremi', pos: 'FWD', img: '' },
            { num: 22, name: 'Mehdi Ghayedi', pos: 'FWD', img: '' },
            { num: 23, name: 'Ali Alipour', pos: 'FWD', img: '' },
            { num: 24, name: 'Amirhossein Hosseinzadeh', pos: 'FWD', img: '' },
            { num: 25, name: 'Shahriyar Moghanloo', pos: 'FWD', img: '' },
            { num: 26, name: 'Dennis Dargahi', pos: 'FWD', img: '' },
        ]
    },
    'Iraq': {
        coach: '', formation: '',
        players: [
            { num: 1, name: 'Fahad Talib', pos: 'GK', img: '' },
            { num: 2, name: 'Jalal Hassan', pos: 'GK', img: '' },
            { num: 3, name: 'Ahmed Basil', pos: 'GK', img: '' },
            { num: 4, name: 'Rebin Sulaka', pos: 'DEF', img: '' },
            { num: 5, name: 'Hussein Ali', pos: 'DEF', img: '' },
            { num: 6, name: 'Zaid Tahseen', pos: 'DEF', img: '' },
            { num: 7, name: 'Akam Hashim', pos: 'DEF', img: '' },
            { num: 8, name: 'Munaf Younus', pos: 'DEF', img: '' },
            { num: 9, name: 'Ahmed Maknazi', pos: 'DEF', img: '' },
            { num: 10, name: 'Merchas Doski', pos: 'DEF', img: '' },
            { num: 11, name: 'Mustafa Saadoon', pos: 'DEF', img: '' },
            { num: 12, name: 'Frans Putros', pos: 'DEF', img: '' },
            { num: 13, name: 'Youssef Amyn', pos: 'MID', img: '' },
            { num: 14, name: 'Ibrahim Bayesh', pos: 'MID', img: '' },
            { num: 15, name: 'Zidane Iqbal', pos: 'MID', img: '' },
            { num: 16, name: 'Amir Alammari', pos: 'MID', img: '' },
            { num: 17, name: 'Kevin Yakob', pos: 'MID', img: '' },
            { num: 18, name: 'Aimar Sher', pos: 'MID', img: '' },
            { num: 19, name: 'Zaid Ismael', pos: 'MID', img: '' },
            { num: 20, name: 'Ali Alhamadi', pos: 'FWD', img: '' },
            { num: 21, name: 'Mohanad Ali', pos: 'FWD', img: '' },
            { num: 22, name: 'Ahmed Qasem', pos: 'FWD', img: '' },
            { num: 23, name: 'Ali Yousif', pos: 'FWD', img: '' },
            { num: 24, name: 'Ali Jasim', pos: 'FWD', img: '' },
            { num: 25, name: 'Aymen Hussein', pos: 'FWD', img: '' },
            { num: 26, name: 'Marko Farji', pos: 'FWD', img: '' },
        ]
    },
    'Ivory Coast': {
        coach: '', formation: '',
        players: [
            { num: 1, name: 'Yahia Fofana', pos: 'GK', img: '' },
            { num: 2, name: 'Mohamed Kone', pos: 'GK', img: '' },
            { num: 3, name: 'Alban Lafont', pos: 'GK', img: '' },
            { num: 4, name: 'Ousmane Diomande', pos: 'DEF', img: '' },
            { num: 5, name: 'Ghislain Konan', pos: 'DEF', img: '' },
            { num: 6, name: 'Wilfried Singo', pos: 'DEF', img: '' },
            { num: 7, name: 'Odilon Kossounou', pos: 'DEF', img: '' },
            { num: 8, name: 'Christopher Operi', pos: 'DEF', img: '' },
            { num: 9, name: 'Guela Doue', pos: 'DEF', img: '' },
            { num: 10, name: 'Emmanuel Agbadou', pos: 'DEF', img: '' },
            { num: 11, name: 'Evan Ndicka', pos: 'DEF', img: '' },
            { num: 12, name: 'Jean Michael Seri', pos: 'MID', img: '' },
            { num: 13, name: 'Seko Fofana', pos: 'MID', img: '' },
            { num: 14, name: 'Franck Kessie', pos: 'MID', img: '' },
            { num: 15, name: 'Ibrahim Sangare', pos: 'MID', img: '' },
            { num: 16, name: 'Parfait Guiagon', pos: 'MID', img: '' },
            { num: 17, name: 'Christ Inao Oulai', pos: 'MID', img: '' },
            { num: 18, name: 'Ange-yoan Bonny', pos: 'FWD', img: '' },
            { num: 19, name: 'Simon Adingra', pos: 'FWD', img: '' },
            { num: 20, name: 'Yan Diomande', pos: 'FWD', img: '' },
            { num: 21, name: 'Elye Wahi', pos: 'FWD', img: '' },
            { num: 22, name: 'Oumar Diakite', pos: 'FWD', img: '' },
            { num: 23, name: 'Amad Diallo', pos: 'FWD', img: '' },
            { num: 24, name: 'Nicolas Pepe', pos: 'FWD', img: '' },
            { num: 25, name: 'Evann Guessand', pos: 'FWD', img: '' },
            { num: 26, name: 'Bazoumana Toure', pos: 'FWD', img: '' },
        ]
    },
    'Japan': {
        coach: '', formation: '',
        players: [
            { num: 1, name: 'Zion Suzuki', pos: 'GK', img: '' },
            { num: 2, name: 'Keisuke Osako', pos: 'GK', img: '' },
            { num: 3, name: 'Tomoki Hayakawa', pos: 'GK', img: '' },
            { num: 4, name: 'Yukinari Sugawara', pos: 'DEF', img: '' },
            { num: 5, name: 'Shogo Taniguchi', pos: 'DEF', img: '' },
            { num: 6, name: 'Kou Itakura', pos: 'DEF', img: '' },
            { num: 7, name: 'Yuto Nagatomo', pos: 'DEF', img: '' },
            { num: 8, name: 'Tsuyoshi Watanabe', pos: 'DEF', img: '' },
            { num: 9, name: 'Ayumu Seko', pos: 'DEF', img: '' },
            { num: 10, name: 'Hiroki Ito', pos: 'DEF', img: '' },
            { num: 11, name: 'Takehiro Tomiyasu', pos: 'DEF', img: '' },
            { num: 12, name: 'Junnosuke Suzuki', pos: 'DEF', img: '' },
            { num: 13, name: 'Ao Tanaka', pos: 'MID', img: '' },
            { num: 14, name: 'Takefusa Kubo', pos: 'MID', img: '' },
            { num: 15, name: 'Ritsu Doan', pos: 'MID', img: '' },
            { num: 16, name: 'Daizen Maeda', pos: 'MID', img: '' },
            { num: 17, name: 'Keito Nakamura', pos: 'MID', img: '' },
            { num: 18, name: 'Junya Ito', pos: 'MID', img: '' },
            { num: 19, name: 'Daichi Kamada', pos: 'MID', img: '' },
            { num: 20, name: 'Yuito Suzuki', pos: 'MID', img: '' },
            { num: 21, name: 'Kaishu Sano', pos: 'MID', img: '' },
            { num: 22, name: 'Shuto Machino', pos: 'FWD', img: '' },
            { num: 23, name: 'Keisuke Goto', pos: 'FWD', img: '' },
            { num: 24, name: 'Ayase Ueda', pos: 'FWD', img: '' },
            { num: 25, name: 'Koki Ogawa', pos: 'FWD', img: '' },
            { num: 26, name: 'Kento Shiogai', pos: 'FWD', img: '' },
        ]
    },
    'Jordan': {
        coach: '', formation: '',
        players: [
            { num: 1, name: 'Yazeed Abulaila', pos: 'GK', img: '' },
            { num: 2, name: 'Nour Baniateyah', pos: 'GK', img: '' },
            { num: 3, name: 'Abdallah Alfakhori', pos: 'GK', img: '' },
            { num: 4, name: 'Mohammad Abuhasheesh', pos: 'DEF', img: '' },
            { num: 5, name: 'Abdallah Nasib', pos: 'DEF', img: '' },
            { num: 6, name: 'Husam Abudahab', pos: 'DEF', img: '' },
            { num: 7, name: 'Yazan Alarab', pos: 'DEF', img: '' },
            { num: 8, name: 'Mohammad Abualnadi', pos: 'DEF', img: '' },
            { num: 9, name: 'Saleem Obaid', pos: 'DEF', img: '' },
            { num: 10, name: 'Saed Alrosan', pos: 'DEF', img: '' },
            { num: 11, name: 'Ehsan Haddad', pos: 'DEF', img: '' },
            { num: 12, name: 'Anas Badawi', pos: 'DEF', img: '' },
            { num: 13, name: 'Amer Jamous', pos: 'MID', img: '' },
            { num: 14, name: 'Noor Alrawabdeh', pos: 'MID', img: '' },
            { num: 15, name: 'Rajaei Ayed', pos: 'MID', img: '' },
            { num: 16, name: 'Ibrahim Sadeh', pos: 'MID', img: '' },
            { num: 17, name: 'Mohammad Abughoush', pos: 'MID', img: '' },
            { num: 18, name: 'Mohannad Abutaha', pos: 'MID', img: '' },
            { num: 19, name: 'Nizar Alrashdan', pos: 'MID', img: '' },
            { num: 20, name: 'Mohammad Aldaoud', pos: 'MID', img: '' },
            { num: 21, name: 'Mohammad Abuzraiq', pos: 'FWD', img: '' },
            { num: 22, name: 'Ali Olwan', pos: 'FWD', img: '' },
            { num: 23, name: 'Mousa Altamari', pos: 'FWD', img: '' },
            { num: 24, name: 'Odeh Fakhoury', pos: 'FWD', img: '' },
            { num: 25, name: 'Mahmoud Almardi', pos: 'FWD', img: '' },
            { num: 26, name: 'Ali Azaizeh', pos: 'FWD', img: '' },
        ]
    },
    'Mexico': {
        coach: '', formation: '',
        players: [
            { num: 1, name: 'Raul Rangel', pos: 'GK', img: '' },
            { num: 2, name: 'Carlos Acevedo', pos: 'GK', img: '' },
            { num: 3, name: 'Guillermo Ochoa', pos: 'GK', img: '' },
            { num: 4, name: 'Jorge Sanchez', pos: 'DEF', img: '' },
            { num: 5, name: 'Cesar Montes', pos: 'DEF', img: '' },
            { num: 6, name: 'Edson Alvarez', pos: 'DEF', img: '' },
            { num: 7, name: 'Johan Vasquez', pos: 'DEF', img: '' },
            { num: 8, name: 'Israel Reyes', pos: 'DEF', img: '' },
            { num: 9, name: 'Mateo Chavez', pos: 'DEF', img: '' },
            { num: 10, name: 'Jesus Gallardo', pos: 'DEF', img: '' },
            { num: 11, name: 'Erik Lira', pos: 'MID', img: '' },
            { num: 12, name: 'Luis Romo', pos: 'MID', img: '' },
            { num: 13, name: 'Alvaro Fidalgo', pos: 'MID', img: '' },
            { num: 14, name: 'Orbelin Pineda', pos: 'MID', img: '' },
            { num: 15, name: 'Obed Vargas', pos: 'MID', img: '' },
            { num: 16, name: 'Gilberto Mora', pos: 'MID', img: '' },
            { num: 17, name: 'Luis Chavez', pos: 'MID', img: '' },
            { num: 18, name: 'Brian Gutierrez', pos: 'MID', img: '' },
            { num: 19, name: 'Raul Jimenez', pos: 'FWD', img: '' },
            { num: 20, name: 'Alexis Vega', pos: 'FWD', img: '' },
            { num: 21, name: 'Santiago Gimenez', pos: 'FWD', img: '' },
            { num: 22, name: 'Armando Gonzalez', pos: 'FWD', img: '' },
            { num: 23, name: 'Julian Quinones', pos: 'FWD', img: '' },
            { num: 24, name: 'Cesar Huerta', pos: 'FWD', img: '' },
            { num: 25, name: 'Guillermo Martinez', pos: 'FWD', img: '' },
            { num: 26, name: 'Roberto Alvarado', pos: 'FWD', img: '' },
        ]
    },
    'Morocco': {
        coach: '', formation: '',
        players: [
            { num: 1, name: 'Yassine Bounou', pos: 'GK', img: '' },
            { num: 2, name: 'Munir El Kajoui', pos: 'GK', img: '' },
            { num: 3, name: 'Ahmed Reda Tagnaouti', pos: 'GK', img: '' },
            { num: 4, name: 'Achraf Hakimi', pos: 'DEF', img: '' },
            { num: 5, name: 'Noussair Mazraoui', pos: 'DEF', img: '' },
            { num: 6, name: 'Marwane Saadane', pos: 'DEF', img: '' },
            { num: 7, name: 'Zakaria El Ouahdi', pos: 'DEF', img: '' },
            { num: 8, name: 'Issa Diop', pos: 'DEF', img: '' },
            { num: 9, name: 'Chadi Riad', pos: 'DEF', img: '' },
            { num: 10, name: 'Youssef Belammari', pos: 'DEF', img: '' },
            { num: 11, name: 'Redouane Halhal', pos: 'DEF', img: '' },
            { num: 12, name: 'Anass Salah Eddine', pos: 'DEF', img: '' },
            { num: 13, name: 'Sofyan Amrabat', pos: 'MID', img: '' },
            { num: 14, name: 'Ayyoub Bouaddi', pos: 'MID', img: '' },
            { num: 15, name: 'Chemsdine Talbi', pos: 'MID', img: '' },
            { num: 16, name: 'Azzedine Ounahi', pos: 'MID', img: '' },
            { num: 17, name: 'Ismael Saibari', pos: 'MID', img: '' },
            { num: 18, name: 'Samir El Mourabet', pos: 'MID', img: '' },
            { num: 19, name: 'Gessime Yassine', pos: 'MID', img: '' },
            { num: 20, name: 'Bilal El Khannouss', pos: 'MID', img: '' },
            { num: 21, name: 'Neil El Aynaoui', pos: 'MID', img: '' },
            { num: 22, name: 'Soufiane Rahimi', pos: 'FWD', img: '' },
            { num: 23, name: 'Brahim Diaz', pos: 'FWD', img: '' },
            { num: 24, name: 'Amine Sbai', pos: 'FWD', img: '' },
            { num: 25, name: 'Ayoub El Kaabi', pos: 'FWD', img: '' },
            { num: 26, name: 'Ayoube Amaimouni', pos: 'FWD', img: '' },
        ]
    },
    'Netherlands': {
        coach: '', formation: '',
        players: [
            { num: 1, name: 'Bart Verbruggen', pos: 'GK', img: '' },
            { num: 2, name: 'Robin Roefs', pos: 'GK', img: '' },
            { num: 3, name: 'Mark Flekken', pos: 'GK', img: '' },
            { num: 4, name: 'Lutsharel Geertruida', pos: 'DEF', img: '' },
            { num: 5, name: 'Virgil Van Dijk', pos: 'DEF', img: '' },
            { num: 6, name: 'Nathan Ake', pos: 'DEF', img: '' },
            { num: 7, name: 'Jan Paul Van Hecke', pos: 'DEF', img: '' },
            { num: 8, name: 'Mats Wieffer', pos: 'DEF', img: '' },
            { num: 9, name: 'Micky Van De Ven', pos: 'DEF', img: '' },
            { num: 10, name: 'Denzel Dumfries', pos: 'DEF', img: '' },
            { num: 11, name: 'Jorrel Hato', pos: 'DEF', img: '' },
            { num: 12, name: 'Marten De Roon', pos: 'MID', img: '' },
            { num: 13, name: 'Justin Kluivert', pos: 'MID', img: '' },
            { num: 14, name: 'Ryan Gravenberch', pos: 'MID', img: '' },
            { num: 15, name: 'Tijjani Reijnders', pos: 'MID', img: '' },
            { num: 16, name: 'Guus Til', pos: 'MID', img: '' },
            { num: 17, name: 'Teun Koopmeiners', pos: 'MID', img: '' },
            { num: 18, name: 'Frenkie De Jong', pos: 'MID', img: '' },
            { num: 19, name: 'Quinten Timber', pos: 'MID', img: '' },
            { num: 20, name: 'Wout Weghorst', pos: 'FWD', img: '' },
            { num: 21, name: 'Memphis Depay', pos: 'FWD', img: '' },
            { num: 22, name: 'Cody Gakpo', pos: 'FWD', img: '' },
            { num: 23, name: 'Noa Lang', pos: 'FWD', img: '' },
            { num: 24, name: 'Donyell Malen', pos: 'FWD', img: '' },
            { num: 25, name: 'Brian Brobbey', pos: 'FWD', img: '' },
            { num: 26, name: 'Crysencio Summerville', pos: 'FWD', img: '' },
        ]
    },
    'New Zealand': {
        coach: '', formation: '',
        players: [
            { num: 1, name: 'Max Crocombe', pos: 'GK', img: '' },
            { num: 2, name: 'Alex Paulsen', pos: 'GK', img: '' },
            { num: 3, name: 'Michael Woud', pos: 'GK', img: '' },
            { num: 4, name: 'Tim Payne', pos: 'DEF', img: '' },
            { num: 5, name: 'Francis De Vries', pos: 'DEF', img: '' },
            { num: 6, name: 'Tyler Bindon', pos: 'DEF', img: '' },
            { num: 7, name: 'Michael Boxall', pos: 'DEF', img: '' },
            { num: 8, name: 'Liberato Cacace', pos: 'DEF', img: '' },
            { num: 9, name: 'Nando Pijnaker', pos: 'DEF', img: '' },
            { num: 10, name: 'Finn Surman', pos: 'DEF', img: '' },
            { num: 11, name: 'Callan Elliot', pos: 'DEF', img: '' },
            { num: 12, name: 'Tommy Smith', pos: 'DEF', img: '' },
            { num: 13, name: 'Joe Bell', pos: 'MID', img: '' },
            { num: 14, name: 'Marko Stamenic', pos: 'MID', img: '' },
            { num: 15, name: 'Sarpreet Singh', pos: 'MID', img: '' },
            { num: 16, name: 'Elijah Just', pos: 'MID', img: '' },
            { num: 17, name: 'Alex Rufer', pos: 'MID', img: '' },
            { num: 18, name: 'Ben Old', pos: 'MID', img: '' },
            { num: 19, name: 'Callum Mccowatt', pos: 'MID', img: '' },
            { num: 20, name: 'Ryan Thomas', pos: 'MID', img: '' },
            { num: 21, name: 'Lachlan Bayliss', pos: 'MID', img: '' },
            { num: 22, name: 'Logan Rogerson', pos: 'FWD', img: '' },
            { num: 23, name: 'Chris Wood', pos: 'FWD', img: '' },
            { num: 24, name: 'Kosta Barbarouses', pos: 'FWD', img: '' },
            { num: 25, name: 'Ben Waine', pos: 'FWD', img: '' },
            { num: 26, name: 'Jesse Randall', pos: 'FWD', img: '' },
        ]
    },
    'Norway': {
        coach: '', formation: '',
        players: [
            { num: 1, name: 'Orjan Nyland', pos: 'GK', img: '' },
            { num: 2, name: 'Sander Tangvik', pos: 'GK', img: '' },
            { num: 3, name: 'Egil Selvik', pos: 'GK', img: '' },
            { num: 4, name: 'Kristoffer Ajer', pos: 'DEF', img: '' },
            { num: 5, name: 'Leo Ostigard', pos: 'DEF', img: '' },
            { num: 6, name: 'David Moller Wolfe', pos: 'DEF', img: '' },
            { num: 7, name: 'Fredrik Andre Bjorkan', pos: 'DEF', img: '' },
            { num: 8, name: 'Marcus Holmgren Pedersen', pos: 'DEF', img: '' },
            { num: 9, name: 'Torbjorn Heggem', pos: 'DEF', img: '' },
            { num: 10, name: 'Sondre Langas', pos: 'DEF', img: '' },
            { num: 11, name: 'Henrik Falchener', pos: 'DEF', img: '' },
            { num: 12, name: 'Morten Thorsby', pos: 'MID', img: '' },
            { num: 13, name: 'Patrick Berg', pos: 'MID', img: '' },
            { num: 14, name: 'Sander Berge', pos: 'MID', img: '' },
            { num: 15, name: 'Martin Odegaard', pos: 'MID', img: '' },
            { num: 16, name: 'Fredrik Aursnes', pos: 'MID', img: '' },
            { num: 17, name: 'Kristian Thorstvedt', pos: 'MID', img: '' },
            { num: 18, name: 'Thelo Aasgaard', pos: 'MID', img: '' },
            { num: 19, name: 'Andreas Schjelderup', pos: 'MID', img: '' },
            { num: 20, name: 'Oscar Bobb', pos: 'MID', img: '' },
            { num: 21, name: 'Jens Petter Hauge', pos: 'MID', img: '' },
            { num: 22, name: 'Alexander Sorloth', pos: 'FWD', img: '' },
            { num: 23, name: 'Erling Haaland', pos: 'FWD', img: '' },
            { num: 24, name: 'Jorgen Strand Larsen', pos: 'FWD', img: '' },
            { num: 25, name: 'Antonio Nusa', pos: 'FWD', img: '' },
            { num: 26, name: 'Julian Ryerson', pos: 'FWD', img: '' },
        ]
    },
    'Panama': {
        coach: '', formation: '',
        players: [
            { num: 1, name: 'Luis Mejia', pos: 'GK', img: '' },
            { num: 2, name: 'Cesar Samudio', pos: 'GK', img: '' },
            { num: 3, name: 'Orlando Mosquera', pos: 'GK', img: '' },
            { num: 4, name: 'Cesar Blackman', pos: 'DEF', img: '' },
            { num: 5, name: 'Jose Cordoba', pos: 'DEF', img: '' },
            { num: 6, name: 'Fidel Escobar', pos: 'DEF', img: '' },
            { num: 7, name: 'Edgardo Farina', pos: 'DEF', img: '' },
            { num: 8, name: 'Jiovany Ramos', pos: 'DEF', img: '' },
            { num: 9, name: 'Carlos Harvey', pos: 'DEF', img: '' },
            { num: 10, name: 'Eric Davis', pos: 'DEF', img: '' },
            { num: 11, name: 'Andres Andrade', pos: 'DEF', img: '' },
            { num: 12, name: 'Amir Murillo', pos: 'DEF', img: '' },
            { num: 13, name: 'Roderick Miller', pos: 'DEF', img: '' },
            { num: 14, name: 'Jorge Gutierrez', pos: 'DEF', img: '' },
            { num: 15, name: 'Cristian Martinez', pos: 'MID', img: '' },
            { num: 16, name: 'Jose Luis Rodriguez', pos: 'MID', img: '' },
            { num: 17, name: 'Adalberto Carrasquilla', pos: 'MID', img: '' },
            { num: 18, name: 'Ismael Diaz', pos: 'MID', img: '' },
            { num: 19, name: 'Edgar Yoel Barcenas', pos: 'MID', img: '' },
            { num: 20, name: 'Alberto Quintero', pos: 'MID', img: '' },
            { num: 21, name: 'Anibal Godoy', pos: 'MID', img: '' },
            { num: 22, name: 'Cesar Yanis', pos: 'MID', img: '' },
            { num: 23, name: 'Tomas Rodriguez', pos: 'FWD', img: '' },
            { num: 24, name: 'Jose Fajardo', pos: 'FWD', img: '' },
            { num: 25, name: 'Cecilio Waterman', pos: 'FWD', img: '' },
            { num: 26, name: 'Azarias Londono', pos: 'FWD', img: '' },
        ]
    },
    'Paraguay': {
        coach: '', formation: '',
        players: [
            { num: 1, name: 'Gatito Fernandez', pos: 'GK', img: '' },
            { num: 2, name: 'Orlando Gill', pos: 'GK', img: '' },
            { num: 3, name: 'Gaston Olveira', pos: 'GK', img: '' },
            { num: 4, name: 'Gustavo Velazquez', pos: 'DEF', img: '' },
            { num: 5, name: 'Omar Alderete', pos: 'DEF', img: '' },
            { num: 6, name: 'Juan Jose Caceres', pos: 'DEF', img: '' },
            { num: 7, name: 'Fabian Balbuena', pos: 'DEF', img: '' },
            { num: 8, name: 'Junior Alonso', pos: 'DEF', img: '' },
            { num: 9, name: 'Jose Canale', pos: 'DEF', img: '' },
            { num: 10, name: 'Gustavo Gomez', pos: 'DEF', img: '' },
            { num: 11, name: 'Alexandro Maidana', pos: 'DEF', img: '' },
            { num: 12, name: 'Ramon Sosa', pos: 'MID', img: '' },
            { num: 13, name: 'Diego Gomez', pos: 'MID', img: '' },
            { num: 14, name: 'Miguel Almiron', pos: 'MID', img: '' },
            { num: 15, name: 'Mauricio', pos: 'MID', img: '' },
            { num: 16, name: 'Andres Cubas', pos: 'MID', img: '' },
            { num: 17, name: 'Damian Bobadilla', pos: 'MID', img: '' },
            { num: 18, name: 'Braian Ojeda', pos: 'MID', img: '' },
            { num: 19, name: 'Matias Galarza', pos: 'MID', img: '' },
            { num: 20, name: 'Gustavo Caballero', pos: 'MID', img: '' },
            { num: 21, name: 'Antonio Sanabria', pos: 'FWD', img: '' },
            { num: 22, name: 'Alejandro Romero Gamarra', pos: 'FWD', img: '' },
            { num: 23, name: 'Alex Arce', pos: 'FWD', img: '' },
            { num: 24, name: 'Julio Enciso', pos: 'FWD', img: '' },
            { num: 25, name: 'Gabriel Avalos', pos: 'FWD', img: '' },
            { num: 26, name: 'Isidro Pitta', pos: 'FWD', img: '' },
        ]
    },
    'Portugal': {
        coach: '', formation: '',
        players: [
            { num: 1, name: 'Diogo Costa', pos: 'GK', img: '' },
            { num: 2, name: 'Jose Sa', pos: 'GK', img: '' },
            { num: 3, name: 'Rui Silva', pos: 'GK', img: '' },
            { num: 4, name: 'Nelson Semedo', pos: 'DEF', img: '' },
            { num: 5, name: 'Ruben Dias', pos: 'DEF', img: '' },
            { num: 6, name: 'Tomas Araujo', pos: 'DEF', img: '' },
            { num: 7, name: 'Diogo Dalot', pos: 'DEF', img: '' },
            { num: 8, name: 'Renato Veiga', pos: 'DEF', img: '' },
            { num: 9, name: 'Goncalo Inacio', pos: 'DEF', img: '' },
            { num: 10, name: 'Joao Cancelo', pos: 'DEF', img: '' },
            { num: 11, name: 'Samu Costa', pos: 'DEF', img: '' },
            { num: 12, name: 'Nuno Mendes', pos: 'DEF', img: '' },
            { num: 13, name: 'Matheus Nunes', pos: 'MID', img: '' },
            { num: 14, name: 'Bruno Fernandes', pos: 'MID', img: '' },
            { num: 15, name: 'Bernardo Silva', pos: 'MID', img: '' },
            { num: 16, name: 'Joao Neves', pos: 'MID', img: '' },
            { num: 17, name: 'Ruben Neves', pos: 'MID', img: '' },
            { num: 18, name: 'Vitinha', pos: 'MID', img: '' },
            { num: 19, name: 'Cristiano Ronaldo', pos: 'FWD', img: '' },
            { num: 20, name: 'Goncalo Ramos', pos: 'FWD', img: '' },
            { num: 21, name: 'Joao Felix', pos: 'FWD', img: '' },
            { num: 22, name: 'Francisco Trincao', pos: 'FWD', img: '' },
            { num: 23, name: 'Rafael Leao', pos: 'FWD', img: '' },
            { num: 24, name: 'Pedro Neto', pos: 'FWD', img: '' },
            { num: 25, name: 'Goncalo Guedes', pos: 'FWD', img: '' },
            { num: 26, name: 'Francisco Conceicao', pos: 'FWD', img: '' },
        ]
    },
    'Qatar': {
        coach: '', formation: '',
        players: [
            { num: 1, name: 'Mahmoud Abunada', pos: 'GK', img: '' },
            { num: 2, name: 'Salah Zakaria', pos: 'GK', img: '' },
            { num: 3, name: 'Meshaal Barsham', pos: 'GK', img: '' },
            { num: 4, name: 'Pedro Miguel', pos: 'DEF', img: '' },
            { num: 5, name: 'Lucas Mendes', pos: 'DEF', img: '' },
            { num: 6, name: 'Issa Laye', pos: 'DEF', img: '' },
            { num: 7, name: 'Jassem Gaber', pos: 'DEF', img: '' },
            { num: 8, name: 'Ayoub Aloui', pos: 'DEF', img: '' },
            { num: 9, name: 'Homam Ahmed', pos: 'DEF', img: '' },
            { num: 10, name: 'Boualem Khoukhi', pos: 'DEF', img: '' },
            { num: 11, name: 'Sultan Albrake', pos: 'DEF', img: '' },
            { num: 12, name: 'Alhashmi Alhussein', pos: 'DEF', img: '' },
            { num: 13, name: 'Abdulaziz Hatem', pos: 'MID', img: '' },
            { num: 14, name: 'Karim Boudiaf', pos: 'MID', img: '' },
            { num: 15, name: 'Ahmed Alganehi', pos: 'MID', img: '' },
            { num: 16, name: 'Ahmed Fathy', pos: 'MID', img: '' },
            { num: 17, name: 'Assim Madibo', pos: 'MID', img: '' },
            { num: 18, name: 'Ahmed Alaaeldin', pos: 'FWD', img: '' },
            { num: 19, name: 'Edmilson Junior', pos: 'FWD', img: '' },
            { num: 20, name: 'Mohammed Muntari', pos: 'FWD', img: '' },
            { num: 21, name: 'Hassan Alhaydos', pos: 'FWD', img: '' },
            { num: 22, name: 'Akram Afif', pos: 'FWD', img: '' },
            { num: 23, name: 'Yusuf Abdurisag', pos: 'FWD', img: '' },
            { num: 24, name: 'Almoez Ali', pos: 'FWD', img: '' },
            { num: 25, name: 'Tahsin Mohammed', pos: 'FWD', img: '' },
            { num: 26, name: 'Mohamed Manai', pos: 'FWD', img: '' },
        ]
    },
    'Saudi Arabia': {
        coach: '', formation: '',
        players: [
            { num: 1, name: 'Nawaf Alaqidi', pos: 'GK', img: '' },
            { num: 2, name: 'Mohammed Alowais', pos: 'GK', img: '' },
            { num: 3, name: 'Ahmed Alkassar', pos: 'GK', img: '' },
            { num: 4, name: 'Ali Majrashi', pos: 'DEF', img: '' },
            { num: 5, name: 'Ali Lajami', pos: 'DEF', img: '' },
            { num: 6, name: 'Abdulelah Alamri', pos: 'DEF', img: '' },
            { num: 7, name: 'Hassan Altambakti', pos: 'DEF', img: '' },
            { num: 8, name: 'Saud Abdulhamid', pos: 'DEF', img: '' },
            { num: 9, name: 'Nawaf Bu Washl', pos: 'DEF', img: '' },
            { num: 10, name: 'Hassan Kadish', pos: 'DEF', img: '' },
            { num: 11, name: 'Moteb Alharbi', pos: 'DEF', img: '' },
            { num: 12, name: 'Jehad Thikri', pos: 'DEF', img: '' },
            { num: 13, name: 'Mohammed Abu Alshamat', pos: 'DEF', img: '' },
            { num: 14, name: 'Nasser Aldawsari', pos: 'MID', img: '' },
            { num: 15, name: 'Musab Aljuwayr', pos: 'MID', img: '' },
            { num: 16, name: 'Abdullah Alkhaibari', pos: 'MID', img: '' },
            { num: 17, name: 'Ziyad Aljohani', pos: 'MID', img: '' },
            { num: 18, name: 'Ala Alhajji', pos: 'MID', img: '' },
            { num: 19, name: 'Mohamed Kanno', pos: 'MID', img: '' },
            { num: 20, name: 'Aiman Yahya', pos: 'FWD', img: '' },
            { num: 21, name: 'Feras Albrikan', pos: 'FWD', img: '' },
            { num: 22, name: 'Salem Aldawsari', pos: 'FWD', img: '' },
            { num: 23, name: 'Saleh Alshehri', pos: 'FWD', img: '' },
            { num: 24, name: 'Khalid Alghannam', pos: 'FWD', img: '' },
            { num: 25, name: 'Abdullah Alhamddan', pos: 'FWD', img: '' },
            { num: 26, name: 'Sultan Mandash', pos: 'FWD', img: '' },
        ]
    },
    'Scotland': {
        coach: '', formation: '',
        players: [
            { num: 1, name: 'Angus Gunn', pos: 'GK', img: '' },
            { num: 2, name: 'Liam Kelly', pos: 'GK', img: '' },
            { num: 3, name: 'Craig Gordon', pos: 'GK', img: '' },
            { num: 4, name: 'Aaron Hickey', pos: 'DEF', img: '' },
            { num: 5, name: 'Andy Robertson', pos: 'DEF', img: '' },
            { num: 6, name: 'Grant Hanley', pos: 'DEF', img: '' },
            { num: 7, name: 'Kieran Tierney', pos: 'DEF', img: '' },
            { num: 8, name: 'Jack Hendry', pos: 'DEF', img: '' },
            { num: 9, name: 'John Souttar', pos: 'DEF', img: '' },
            { num: 10, name: 'Dominic Hyam', pos: 'DEF', img: '' },
            { num: 11, name: 'Nathan Patterson', pos: 'DEF', img: '' },
            { num: 12, name: 'Anthony Ralston', pos: 'DEF', img: '' },
            { num: 13, name: 'Scott Mckenna', pos: 'DEF', img: '' },
            { num: 14, name: 'Scott Mctominay', pos: 'MID', img: '' },
            { num: 15, name: 'John Mcginn', pos: 'MID', img: '' },
            { num: 16, name: 'Tyler Fletcher', pos: 'MID', img: '' },
            { num: 17, name: 'Ryan Christie', pos: 'MID', img: '' },
            { num: 18, name: 'Lewis Ferguson', pos: 'MID', img: '' },
            { num: 19, name: 'Kenny Mclean', pos: 'MID', img: '' },
            { num: 20, name: 'Lyndon Dykes', pos: 'FWD', img: '' },
            { num: 21, name: 'Che Adams', pos: 'FWD', img: '' },
            { num: 22, name: 'Ross Stewart', pos: 'FWD', img: '' },
            { num: 23, name: 'Ben Gannon-doak', pos: 'FWD', img: '' },
            { num: 24, name: 'George Hirst', pos: 'FWD', img: '' },
            { num: 25, name: 'Lawrence Shankland', pos: 'FWD', img: '' },
            { num: 26, name: 'Findlay Curtis', pos: 'FWD', img: '' },
        ]
    },
    'Senegal': {
        coach: '', formation: '',
        players: [
            { num: 1, name: 'Yehvann Diouf', pos: 'GK', img: '' },
            { num: 2, name: 'Edouard Mendy', pos: 'GK', img: '' },
            { num: 3, name: 'Mory Diaw', pos: 'GK', img: '' },
            { num: 4, name: 'Mamadou Sarr', pos: 'DEF', img: '' },
            { num: 5, name: 'Kalidou Koulibaly', pos: 'DEF', img: '' },
            { num: 6, name: 'Abdoulaye Seck', pos: 'DEF', img: '' },
            { num: 7, name: 'Ismail Jakobs', pos: 'DEF', img: '' },
            { num: 8, name: 'Krepin Diatta', pos: 'DEF', img: '' },
            { num: 9, name: 'Moussa Niakhate', pos: 'DEF', img: '' },
            { num: 10, name: 'Antoine Mendy', pos: 'DEF', img: '' },
            { num: 11, name: 'El Hadji Malick Diouf', pos: 'DEF', img: '' },
            { num: 12, name: 'Idrissa Gana Gueye', pos: 'MID', img: '' },
            { num: 13, name: 'Pathe Ciss', pos: 'MID', img: '' },
            { num: 14, name: 'Lamine Camara', pos: 'MID', img: '' },
            { num: 15, name: 'Pape Matar Sarr', pos: 'MID', img: '' },
            { num: 16, name: 'Habib Diarra', pos: 'MID', img: '' },
            { num: 17, name: 'Bara Sapoko Ndiaye', pos: 'MID', img: '' },
            { num: 18, name: 'Pape Gueye', pos: 'MID', img: '' },
            { num: 19, name: 'Assane Diao', pos: 'FWD', img: '' },
            { num: 20, name: 'Bamba Dieng', pos: 'FWD', img: '' },
            { num: 21, name: 'Sadio Mane', pos: 'FWD', img: '' },
            { num: 22, name: 'Nicolas Jackson', pos: 'FWD', img: '' },
            { num: 23, name: 'Cherif Ndiaye', pos: 'FWD', img: '' },
            { num: 24, name: 'Iliman Ndiaye', pos: 'FWD', img: '' },
            { num: 25, name: 'Ismaila Sarr', pos: 'FWD', img: '' },
            { num: 26, name: 'Ibrahim Mbaye', pos: 'FWD', img: '' },
        ]
    },
    'South Africa': {
        coach: '', formation: '',
        players: [
            { num: 1, name: 'Ronwen Williams', pos: 'GK', img: '' },
            { num: 2, name: 'Sipho Chaine', pos: 'GK', img: '' },
            { num: 3, name: 'Ricardo Goss', pos: 'GK', img: '' },
            { num: 4, name: 'Thabang Matuludi', pos: 'DEF', img: '' },
            { num: 5, name: 'Khulumani Ndamane', pos: 'DEF', img: '' },
            { num: 6, name: 'Aubrey Modiba', pos: 'DEF', img: '' },
            { num: 7, name: 'Mbekezeli Mbokazi', pos: 'DEF', img: '' },
            { num: 8, name: 'Samukele Kabini', pos: 'DEF', img: '' },
            { num: 9, name: 'Nkosinathi Sibisi', pos: 'DEF', img: '' },
            { num: 10, name: 'Khuliso Mudau', pos: 'DEF', img: '' },
            { num: 11, name: 'Ime Okon', pos: 'DEF', img: '' },
            { num: 12, name: 'Olwethu Makhanya', pos: 'DEF', img: '' },
            { num: 13, name: 'Bradley Cross', pos: 'DEF', img: '' },
            { num: 14, name: 'Teboho Mokoena', pos: 'MID', img: '' },
            { num: 15, name: 'Thalente Mbatha', pos: 'MID', img: '' },
            { num: 16, name: 'Themba Zwane', pos: 'MID', img: '' },
            { num: 17, name: 'Sphephelo Sithole', pos: 'MID', img: '' },
            { num: 18, name: 'Jayden Adams', pos: 'MID', img: '' },
            { num: 19, name: 'Oswin Appollis', pos: 'FWD', img: '' },
            { num: 20, name: 'Tshepang Moremi', pos: 'FWD', img: '' },
            { num: 21, name: 'Lyle Foster', pos: 'FWD', img: '' },
            { num: 22, name: 'Relebohile Mofokeng', pos: 'FWD', img: '' },
            { num: 23, name: 'Thapelo Maseko', pos: 'FWD', img: '' },
            { num: 24, name: 'Iqraam Rayners', pos: 'FWD', img: '' },
            { num: 25, name: 'Evidence Makgopa', pos: 'FWD', img: '' },
            { num: 26, name: 'Kamogelo Sebelebele', pos: 'FWD', img: '' },
        ]
    },
    'South Korea': {
        coach: '', formation: '',
        players: [
            { num: 1, name: 'Kim Seunggyu', pos: 'GK', img: '' },
            { num: 2, name: 'Song Bumkeun', pos: 'GK', img: '' },
            { num: 3, name: 'Jo Hyeonwoo', pos: 'GK', img: '' },
            { num: 4, name: 'Lee Hanbeom', pos: 'DEF', img: '' },
            { num: 5, name: 'Kim Minjae', pos: 'DEF', img: '' },
            { num: 6, name: 'Kim Taehyeon', pos: 'DEF', img: '' },
            { num: 7, name: 'Lee Taeseok', pos: 'DEF', img: '' },
            { num: 8, name: 'Cho Wije', pos: 'DEF', img: '' },
            { num: 9, name: 'Kim Moonhwan', pos: 'DEF', img: '' },
            { num: 10, name: 'Park Jinseob', pos: 'DEF', img: '' },
            { num: 11, name: 'Seol Youngwoo', pos: 'DEF', img: '' },
            { num: 12, name: 'Castrop Jens', pos: 'DEF', img: '' },
            { num: 13, name: 'Lee Gihyuk', pos: 'MID', img: '' },
            { num: 14, name: 'Hwang Inbeom', pos: 'MID', img: '' },
            { num: 15, name: 'Paik Seungho', pos: 'MID', img: '' },
            { num: 16, name: 'Lee Jaesung', pos: 'MID', img: '' },
            { num: 17, name: 'Hwang Heechan', pos: 'MID', img: '' },
            { num: 18, name: 'Bae Junho', pos: 'MID', img: '' },
            { num: 19, name: 'Lee Kangin', pos: 'MID', img: '' },
            { num: 20, name: 'Yang Hyunjun', pos: 'MID', img: '' },
            { num: 21, name: 'Kim Jingyu', pos: 'MID', img: '' },
            { num: 22, name: 'Eom Jisung', pos: 'MID', img: '' },
            { num: 23, name: 'Lee Donggyeong', pos: 'MID', img: '' },
            { num: 24, name: 'Son Heungmin', pos: 'FWD', img: '' },
            { num: 25, name: 'Cho Guesung', pos: 'FWD', img: '' },
            { num: 26, name: 'Oh Hyeongyu', pos: 'FWD', img: '' },
        ]
    },
    'Spain': {
        coach: '', formation: '',
        players: [
            { num: 1, name: 'David Raya', pos: 'GK', img: '' },
            { num: 2, name: 'Joan Garcia', pos: 'GK', img: '' },
            { num: 3, name: 'Unai Simon', pos: 'GK', img: '' },
            { num: 4, name: 'Marc Pubill', pos: 'DEF', img: '' },
            { num: 5, name: 'Alex Grimaldo', pos: 'DEF', img: '' },
            { num: 6, name: 'Eric Garcia', pos: 'DEF', img: '' },
            { num: 7, name: 'Marcos Llorente', pos: 'DEF', img: '' },
            { num: 8, name: 'Pedro Porro', pos: 'DEF', img: '' },
            { num: 9, name: 'Aymeric Laporte', pos: 'DEF', img: '' },
            { num: 10, name: 'Pau Cubarsi', pos: 'DEF', img: '' },
            { num: 11, name: 'Marc Cucurella', pos: 'DEF', img: '' },
            { num: 12, name: 'Mikel Merino', pos: 'MID', img: '' },
            { num: 13, name: 'Fabian Ruiz', pos: 'MID', img: '' },
            { num: 14, name: 'Gavi', pos: 'MID', img: '' },
            { num: 15, name: 'Alex Baena', pos: 'MID', img: '' },
            { num: 16, name: 'Rodri', pos: 'MID', img: '' },
            { num: 17, name: 'Martin Zubimendi', pos: 'MID', img: '' },
            { num: 18, name: 'Pedri', pos: 'MID', img: '' },
            { num: 19, name: 'Ferran Torres', pos: 'FWD', img: '' },
            { num: 20, name: 'Dani Olmo', pos: 'FWD', img: '' },
            { num: 21, name: 'Yeremy Pino', pos: 'FWD', img: '' },
            { num: 22, name: 'Nico Williams', pos: 'FWD', img: '' },
            { num: 23, name: 'Lamine Yamal', pos: 'FWD', img: '' },
            { num: 24, name: 'Mikel Oyarzabal', pos: 'FWD', img: '' },
            { num: 25, name: 'Victor Munoz', pos: 'FWD', img: '' },
            { num: 26, name: 'Borja Iglesias', pos: 'FWD', img: '' },
        ]
    },
    'Sweden': {
        coach: '', formation: '',
        players: [
            { num: 1, name: 'Jacob Widell Zetterstrom', pos: 'GK', img: '' },
            { num: 2, name: 'Viktor Johansson', pos: 'GK', img: '' },
            { num: 3, name: 'Kristoffer Nordfeldt', pos: 'GK', img: '' },
            { num: 4, name: 'Gustaf Lagerbielke', pos: 'DEF', img: '' },
            { num: 5, name: 'Victor Lindelof', pos: 'DEF', img: '' },
            { num: 6, name: 'Isak Hien', pos: 'DEF', img: '' },
            { num: 7, name: 'Gabriel Gudmundsson', pos: 'DEF', img: '' },
            { num: 8, name: 'Herman Johansson', pos: 'DEF', img: '' },
            { num: 9, name: 'Daniel Svensson', pos: 'DEF', img: '' },
            { num: 10, name: 'Hjalmar Ekdal', pos: 'DEF', img: '' },
            { num: 11, name: 'Carl Starfelt', pos: 'DEF', img: '' },
            { num: 12, name: 'Eric Smith', pos: 'DEF', img: '' },
            { num: 13, name: 'Alexander Bernhardsson', pos: 'DEF', img: '' },
            { num: 14, name: 'Elliot Stroud', pos: 'DEF', img: '' },
            { num: 15, name: 'Lucas Bergvall', pos: 'MID', img: '' },
            { num: 16, name: 'Benjamin Nygren', pos: 'MID', img: '' },
            { num: 17, name: 'Ken Sema', pos: 'MID', img: '' },
            { num: 18, name: 'Jesper Karlstrom', pos: 'MID', img: '' },
            { num: 19, name: 'Yasin Ayari', pos: 'MID', img: '' },
            { num: 20, name: 'Mattias Svanberg', pos: 'MID', img: '' },
            { num: 21, name: 'Besfort Zeneli', pos: 'MID', img: '' },
            { num: 22, name: 'Alexander Isak', pos: 'FWD', img: '' },
            { num: 23, name: 'Anthony Elanga', pos: 'FWD', img: '' },
            { num: 24, name: 'Viktor Gyokeres', pos: 'FWD', img: '' },
            { num: 25, name: 'Gustaf Nilsson', pos: 'FWD', img: '' },
            { num: 26, name: 'Taha Ali', pos: 'FWD', img: '' },
        ]
    },
    'Switzerland': {
        coach: '', formation: '',
        players: [
            { num: 1, name: 'Gregor Kobel', pos: 'GK', img: '' },
            { num: 2, name: 'Yvon Mvogo', pos: 'GK', img: '' },
            { num: 3, name: 'Marvin Keller', pos: 'GK', img: '' },
            { num: 4, name: 'Miro Muheim', pos: 'DEF', img: '' },
            { num: 5, name: 'Silvan Widmer', pos: 'DEF', img: '' },
            { num: 6, name: 'Nico Elvedi', pos: 'DEF', img: '' },
            { num: 7, name: 'Manuel Akanji', pos: 'DEF', img: '' },
            { num: 8, name: 'Ricardo Rodriguez', pos: 'DEF', img: '' },
            { num: 9, name: 'Eray Coemert', pos: 'DEF', img: '' },
            { num: 10, name: 'Aurele Amenda', pos: 'DEF', img: '' },
            { num: 11, name: 'Luca Jaquez', pos: 'DEF', img: '' },
            { num: 12, name: 'Denis Zakaria', pos: 'MID', img: '' },
            { num: 13, name: 'Remo Freuler', pos: 'MID', img: '' },
            { num: 14, name: 'Johan Manzambi', pos: 'MID', img: '' },
            { num: 15, name: 'Granit Xhaka', pos: 'MID', img: '' },
            { num: 16, name: 'Ardon Jashari', pos: 'MID', img: '' },
            { num: 17, name: 'Djibril Sow', pos: 'MID', img: '' },
            { num: 18, name: 'Michel Aebischer', pos: 'MID', img: '' },
            { num: 19, name: 'Fabian Rieder', pos: 'MID', img: '' },
            { num: 20, name: 'Breel Embolo', pos: 'FWD', img: '' },
            { num: 21, name: 'Dan Ndoye', pos: 'FWD', img: '' },
            { num: 22, name: 'Christian Fassnacht', pos: 'FWD', img: '' },
            { num: 23, name: 'Ruben Vargas', pos: 'FWD', img: '' },
            { num: 24, name: 'Noah Okafor', pos: 'FWD', img: '' },
            { num: 25, name: 'Zeki Amdouni', pos: 'FWD', img: '' },
            { num: 26, name: 'Cedric Itten', pos: 'FWD', img: '' },
        ]
    },
    'Tunisia': {
        coach: '', formation: '',
        players: [
            { num: 1, name: 'Mouhib Chamakh', pos: 'GK', img: '' },
            { num: 2, name: 'Aymen Dahmen', pos: 'GK', img: '' },
            { num: 3, name: 'Sabri Ben Hessen', pos: 'GK', img: '' },
            { num: 4, name: 'Ali Abdi', pos: 'DEF', img: '' },
            { num: 5, name: 'Montassar Talbi', pos: 'DEF', img: '' },
            { num: 6, name: 'Omar Rekik', pos: 'DEF', img: '' },
            { num: 7, name: 'Adam Arous', pos: 'DEF', img: '' },
            { num: 8, name: 'Dylan Bronn', pos: 'DEF', img: '' },
            { num: 9, name: 'Mortadha Ben Ouanes', pos: 'DEF', img: '' },
            { num: 10, name: 'Yan Valery', pos: 'DEF', img: '' },
            { num: 11, name: 'Mohamed Amine Ben Hmida', pos: 'DEF', img: '' },
            { num: 12, name: 'Moutaz Neffati', pos: 'DEF', img: '' },
            { num: 13, name: 'Raed Chikhaoui', pos: 'DEF', img: '' },
            { num: 14, name: 'Hannibal Mejbri', pos: 'MID', img: '' },
            { num: 15, name: 'Ismael Gharbi', pos: 'MID', img: '' },
            { num: 16, name: 'Rani Khedira', pos: 'MID', img: '' },
            { num: 17, name: 'Khalil Ayari', pos: 'MID', img: '' },
            { num: 18, name: 'Mohamed Hadj Mahmoud', pos: 'MID', img: '' },
            { num: 19, name: 'Ellyes Skhiri', pos: 'MID', img: '' },
            { num: 20, name: 'Anis Slimane', pos: 'MID', img: '' },
            { num: 21, name: 'Sebastian Tounekti', pos: 'MID', img: '' },
            { num: 22, name: 'Elias Achouri', pos: 'FWD', img: '' },
            { num: 23, name: 'Elias Saad', pos: 'FWD', img: '' },
            { num: 24, name: 'Hazem Mastouri', pos: 'FWD', img: '' },
            { num: 25, name: 'Rayan Elloumi', pos: 'FWD', img: '' },
            { num: 26, name: 'Firas Chaouat', pos: 'FWD', img: '' },
        ]
    },
    'Türkiye': {
        coach: '', formation: '',
        players: [
            { num: 1, name: 'Mert Gunok', pos: 'GK', img: '' },
            { num: 2, name: 'Altay Bayindir', pos: 'GK', img: '' },
            { num: 3, name: 'Ugurcan Cakir', pos: 'GK', img: '' },
            { num: 4, name: 'Zeki Celik', pos: 'DEF', img: '' },
            { num: 5, name: 'Merih Demiral', pos: 'DEF', img: '' },
            { num: 6, name: 'Caglar Soyuncu', pos: 'DEF', img: '' },
            { num: 7, name: 'Eren Elmali', pos: 'DEF', img: '' },
            { num: 8, name: 'Abdulkerim Bardakci', pos: 'DEF', img: '' },
            { num: 9, name: 'Ozan Kabak', pos: 'DEF', img: '' },
            { num: 10, name: 'Mert Muldur', pos: 'DEF', img: '' },
            { num: 11, name: 'Ferdi Kadioglu', pos: 'DEF', img: '' },
            { num: 12, name: 'Samet Akaydin', pos: 'DEF', img: '' },
            { num: 13, name: 'Salih Ozcan', pos: 'MID', img: '' },
            { num: 14, name: 'Orkun Kokcu', pos: 'MID', img: '' },
            { num: 15, name: 'Hakan Calhanoglu', pos: 'MID', img: '' },
            { num: 16, name: 'Ismail Yuksek', pos: 'MID', img: '' },
            { num: 17, name: 'Kaan Ayhan', pos: 'MID', img: '' },
            { num: 18, name: 'Kerem Akturkoglu', pos: 'FWD', img: '' },
            { num: 19, name: 'Arda Guler', pos: 'FWD', img: '' },
            { num: 20, name: 'Deniz Gul', pos: 'FWD', img: '' },
            { num: 21, name: 'Kenan Yildiz', pos: 'FWD', img: '' },
            { num: 22, name: 'Irfan Can Kahveci', pos: 'FWD', img: '' },
            { num: 23, name: 'Yunus Akgun', pos: 'FWD', img: '' },
            { num: 24, name: 'Baris Alper Yilmaz', pos: 'FWD', img: '' },
            { num: 25, name: 'Oguz Aydin', pos: 'FWD', img: '' },
            { num: 26, name: 'Can Uzun', pos: 'FWD', img: '' },
        ]
    },
    'USA': {
        coach: '', formation: '',
        players: [
            { num: 1, name: 'Matt Turner', pos: 'GK', img: '' },
            { num: 2, name: 'Matt Freese', pos: 'GK', img: '' },
            { num: 3, name: 'Chris Brady', pos: 'GK', img: '' },
            { num: 4, name: 'Sergino Dest', pos: 'DEF', img: '' },
            { num: 5, name: 'Chris Richards', pos: 'DEF', img: '' },
            { num: 6, name: 'Antonee Robinson', pos: 'DEF', img: '' },
            { num: 7, name: 'Auston Trusty', pos: 'DEF', img: '' },
            { num: 8, name: 'Miles Robinson', pos: 'DEF', img: '' },
            { num: 9, name: 'Tim Ream', pos: 'DEF', img: '' },
            { num: 10, name: 'Alex Freeman', pos: 'DEF', img: '' },
            { num: 11, name: 'Max Arfsten', pos: 'DEF', img: '' },
            { num: 12, name: 'Mark Mckenzie', pos: 'DEF', img: '' },
            { num: 13, name: 'Joe Scally', pos: 'DEF', img: '' },
            { num: 14, name: 'Tyler Adams', pos: 'MID', img: '' },
            { num: 15, name: 'Giovanni Reyna', pos: 'MID', img: '' },
            { num: 16, name: 'Weston Mckennie', pos: 'MID', img: '' },
            { num: 17, name: 'Sebastian Berhalter', pos: 'MID', img: '' },
            { num: 18, name: 'Cristian Roldan', pos: 'MID', img: '' },
            { num: 19, name: 'Malik Tillman', pos: 'MID', img: '' },
            { num: 20, name: 'Ricardo Pepi', pos: 'FWD', img: '' },
            { num: 21, name: 'Christian Pulisic', pos: 'FWD', img: '' },
            { num: 22, name: 'Brenden Aaronson', pos: 'FWD', img: '' },
            { num: 23, name: 'Haji Wright', pos: 'FWD', img: '' },
            { num: 24, name: 'Folarin Balogun', pos: 'FWD', img: '' },
            { num: 25, name: 'Timothy Weah', pos: 'FWD', img: '' },
            { num: 26, name: 'Alex Zendejas', pos: 'FWD', img: '' },
        ]
    },
    'Uruguay': {
        coach: '', formation: '',
        players: [
            { num: 1, name: 'Sergio Rochet', pos: 'GK', img: '' },
            { num: 2, name: 'Santiago Mele', pos: 'GK', img: '' },
            { num: 3, name: 'Fernando Muslera', pos: 'GK', img: '' },
            { num: 4, name: 'Jose Maria Gimenez', pos: 'DEF', img: '' },
            { num: 5, name: 'Sebastian Caceres', pos: 'DEF', img: '' },
            { num: 6, name: 'Ronald Araujo', pos: 'DEF', img: '' },
            { num: 7, name: 'Guillermo Varela', pos: 'DEF', img: '' },
            { num: 8, name: 'Mathias Olivera', pos: 'DEF', img: '' },
            { num: 9, name: 'Matias Vina', pos: 'DEF', img: '' },
            { num: 10, name: 'Santiago Bueno', pos: 'DEF', img: '' },
            { num: 11, name: 'Manuel Ugarte', pos: 'MID', img: '' },
            { num: 12, name: 'Rodrigo Bentancur', pos: 'MID', img: '' },
            { num: 13, name: 'Nicolas De La Cruz', pos: 'MID', img: '' },
            { num: 14, name: 'Federico Valverde', pos: 'MID', img: '' },
            { num: 15, name: 'Giorgian De Arrascaeta', pos: 'MID', img: '' },
            { num: 16, name: 'Agustin Canobbio', pos: 'MID', img: '' },
            { num: 17, name: 'Emiliano Martinez', pos: 'MID', img: '' },
            { num: 18, name: 'Maxi Araujo', pos: 'MID', img: '' },
            { num: 19, name: 'Joaquin Piquerez', pos: 'MID', img: '' },
            { num: 20, name: 'Juan Manuel Sanabria', pos: 'MID', img: '' },
            { num: 21, name: 'Rodrigo Zalazar', pos: 'MID', img: '' },
            { num: 22, name: 'Darwin Nunez', pos: 'FWD', img: '' },
            { num: 23, name: 'Facundo Pellistri', pos: 'FWD', img: '' },
            { num: 24, name: 'Brian Rodriguez', pos: 'FWD', img: '' },
            { num: 25, name: 'Rodrigo Aguirre', pos: 'FWD', img: '' },
            { num: 26, name: 'Federico Vinas', pos: 'FWD', img: '' },
        ]
    },
    'Uzbekistan': {
        coach: '', formation: '',
        players: [
            { num: 1, name: 'Utkir Yusupov', pos: 'GK', img: '' },
            { num: 2, name: 'Abduvohid Nematov', pos: 'GK', img: '' },
            { num: 3, name: 'Botirali Ergashev', pos: 'GK', img: '' },
            { num: 4, name: 'Abdukodir Khusanov', pos: 'DEF', img: '' },
            { num: 5, name: 'Khojiakbar Alijonov', pos: 'DEF', img: '' },
            { num: 6, name: 'Farrukh Sayfiev', pos: 'DEF', img: '' },
            { num: 7, name: 'Rustam Ashurmatov', pos: 'DEF', img: '' },
            { num: 8, name: 'Sherzod Nasrullaev', pos: 'DEF', img: '' },
            { num: 9, name: 'Umar Eshmurodov', pos: 'DEF', img: '' },
            { num: 10, name: 'Abdulla Abdullaev', pos: 'DEF', img: '' },
            { num: 11, name: 'Behruzjon Karimov', pos: 'DEF', img: '' },
            { num: 12, name: 'Avazbek Ulmasaliyev', pos: 'DEF', img: '' },
            { num: 13, name: 'Jakhongir Urozov', pos: 'DEF', img: '' },
            { num: 14, name: 'Akmal Mozgovoy', pos: 'MID', img: '' },
            { num: 15, name: 'Otabek Shukurov', pos: 'MID', img: '' },
            { num: 16, name: 'Jamshid Iskanderov', pos: 'MID', img: '' },
            { num: 17, name: 'Odiljon Xamrobekov', pos: 'MID', img: '' },
            { num: 18, name: 'Jaloliddin Masharipov', pos: 'MID', img: '' },
            { num: 19, name: 'Oston Urunov', pos: 'MID', img: '' },
            { num: 20, name: 'Dostonbek Khamdamov', pos: 'MID', img: '' },
            { num: 21, name: 'Azizjon Ganiev', pos: 'MID', img: '' },
            { num: 22, name: 'Abbosbek Fayzullaev', pos: 'MID', img: '' },
            { num: 23, name: 'Sherzod Esanov', pos: 'MID', img: '' },
            { num: 24, name: 'Eldor Shomurodov', pos: 'FWD', img: '' },
            { num: 25, name: 'Azizbek Amonov', pos: 'FWD', img: '' },
            { num: 26, name: 'Igor Sergeev', pos: 'FWD', img: '' },
        ]
    },
};